// ─── Scientific Revolution 1543-1687 · LENS 1: Isaac Newton (perpetrator-actor) ─────
//
// Topic: Scientific Revolution 1543-1687 · 科学革命
// HSS-7 · AP World 3.4 (Scientific Revolution as cross-cultural knowledge synthesis)
//
// Lens 1 设计:
//   - id: 'newton'
//   - role: 'perpetrator-actor'
//   - perspectiveTag: 'system-builder-alchemist-Mint-enforcer'
//
// 不是「理性时代英雄」也不是「孤胆天才」——是极致系统构建者 + 25 年炼金术 +
// 神学异端 (Arianism) + Mint Warden 亲手送 28 人绞架 + Hooke/Leibniz/Flamsteed
// 终生学术暴力——同一个人. Sarah Chen 7.5/10 audit 后产出.
//
// 跨 lens micro-detail (Sarah audit 锁定 3 个):
//   1. 1644 Mersenne→Pascal→Newton 流体力学链 (N6)
//   2. 1687.7.5《Principia》出版当天三 lens 时间不齐切片 (N7)
//   3. 1710-1712 Berlin 拒 Maria + Cambridge 开除 Whiston (N10)
//
// Cross-Topic 5+1 缝合:
//   - algebra ← Islamic Rise (al-Khwarizmi 825) → N6 / N7
//   - 印刷术 ← Renaissance (1455 Gutenberg) → N6
//   - Erasmus 通信网 ← Reformation → Mersenne → Royal Society 1660 → N7
//   - Galileo 1633 软禁 vs Su Shi 1080 黄州 ← Tang-Song → N10 cross-ref
//   - Newton elixir ← al-iksir ← Islamic Rise (Jabir ibn Hayyan 750-815) → N5
//   - bonus: 5 文明 perpetrator-actor 收尾 → N12
//
// 严格规则:
//   - 不用 *italic* markdown — 外语词 bare + inline gloss
//   - 内嵌引号: 「」(CN) / "..." (EN), 严禁 «...»
//   - em-dash 「——」 ≤ 2 per 段
//   - 每 node 350-550 CN chars (强控)
//   - expectsRealAnswer 默认 false, 只 N11+N12 true
//   - anti-fab: Westfall 1980 / Manuel 1968 / Iliffe 2017 / Gleick 2003 /
//     Keynes 1947 / Smith 2004 / Hall 1962 / Levenson 2009
//   - 数学一致: 1643.1.4 出生 (新历) / 1665-66 anni mirabiles 22-23 / 1687.7.5
//     出版 44 / 1693.9 Black Year 50 / 1696.4 Mint Warden 53 / 1727 死 84

export var newtonLens = {
  id: 'newton',
  name: 'Isaac Newton',
  nameCn: '艾萨克·牛顿',
  role: 'perpetrator-actor',
  perspectiveTag: 'system-builder-alchemist-Mint-enforcer',
  description: {
    en: 'You are Isaac Newton (1643-1727). Your father, an illiterate ploughman, died three months before you were born. At three your mother left to remarry; you were raised by a grandmother. At 22-23 you sketched calculus, optics, and gravity in eighteen plague-shut months. At 44 you published the Principia. You spent 25 years burning a furnace behind Trinity College for the Philosopher\'s Stone, wrote 1.3 million words of Arian heresy in private while signing Anglican oaths in public, sent 28+ counterfeiters to the Tyburn gallows as Mint Warden, and used the Royal Society presidency to crush Hooke, Leibniz, and Flamsteed. Extreme system-builder and systematic violence — the same person.',
    cn: '你是艾萨克·牛顿（1643-1727）。父亲是文盲农夫，你出生前 3 个月死。3 岁时母亲改嫁离开，你被外婆养大。22-23 岁那 18 个月鼠疫关校，你在老家草稿了微积分、光学、引力雏形。44 岁出版《Principia》。同时你在 Trinity 后院烧了 25 年炼金炉子找贤者之石，私下写了 130 万字反三位一体 (Arianism) 神学手稿但公开宣誓 Anglican 正统，当 Mint Warden 亲手送 28+ 个伪币犯上 Tyburn 绞架，用 Royal Society 主席权位碾压 Hooke、Leibniz、Flamsteed。极致系统构建者，同时是系统性暴力的执行者——同一个人。',
  },
  storyboard: [
    {
      id: 'newton-n1',
      type: 'narrative',
      content: {
        cn: '1643.1.4（新历）我生在 Lincolnshire 的 Woolsthorpe Manor。父亲 Isaac Newton Sr. 是文盲农夫（ploughman），1642.10 死，我出生前 3 月。母亲 Hannah Ayscough 怀着我守寡。\n\ncareful framing：当时英国还在用儒略历（比 Gregorian 公历晚 10 天），所以英国人记我「生于圣诞节 1642」。同年 1.8 Galileo 死。Voltaire 1734《Letters on the English》写「Newton 生在 Galileo 死的那年」——这是 Voltaire 构造的 Whig 火炬传递史诗，不要照单全收。我跟 Galileo 时差 16 天但隔了一整套历法系统。\n\n我活了 84 岁——一个出生时被认为活不过几小时的早产婴儿。母亲后来回忆早产的我能装进 1 quart 壶里。1643 年的我——一个文盲农夫的遗腹子。',
        en: 'Born January 4, 1643 (Gregorian) at Woolsthorpe Manor, Lincolnshire. My father Isaac Newton Sr., an illiterate ploughman, died October 1642 — three months before me. My mother Hannah Ayscough was a pregnant widow.\n\nCareful framing: England was still using the Julian calendar (10 days behind Gregorian), so the English wrote "born Christmas 1642." Galileo died that same January 8. Voltaire\'s 1734 Letters on the English claimed "Newton was born the year Galileo died" — a Whig torch-passing epic Voltaire constructed. Galileo and I are 16 days apart but separated by an entire calendar system.\n\nI lived 84 years — a premature baby no one expected to survive. My mother recalled the newborn me could fit inside a one-quart pot. In 1643, the posthumous son of an illiterate farmer.',
      },
      deliverGoal: 'N1 hook — 1643.1.4 出生 (新历 vs 旧历 careful framing) + 父亲 ploughman 死 + Voltaire 火炬传递 Whig + 1 quart 壶早产活 84',
      engagementHook: 'Voltaire 把我跟 Galileo 串成「火炬传递」——但我们隔了一整套历法系统。你怎么读「后世构造的连续性」？',
      expectsRealAnswer: false,
    },
    {
      id: 'newton-n2',
      type: 'narrative',
      content: {
        cn: '1646 我 3 岁，母亲改嫁 Barnabas Smith——一个 63 岁有钱牧师。Smith 不要我。母亲把我留给外婆 Margery Ayscough 在 Woolsthorpe 养，自己搬去 Smith 家又生 3 个孩子。\n\nFrank Manuel 1968《A Portrait of Isaac Newton》ch. 9 用精神分析解读：我一辈子 paranoid + 报复型人格 + 终生未婚 + 跟 Hooke/Leibniz/Flamsteed 学术死战，根源在 3 岁被母亲抛弃。Manuel 是 1960s 框架，现代史学家不全部接受这条因果链——但我 19 岁笔记本自己写过一条罪过：「Threatening my father and mother Smith to burne them and the house over them」（威胁要烧死 Smith + 母亲 + 房子）。这是我自己写的，不是后人猜的。\n\n1659 Smith 死，母亲召我回 Woolsthorpe 务农 16 岁。我务农彻底失败：牛跑了我在树下读书。舅舅 William Ayscough（剑桥牧师）说服母亲送我 Cambridge。1661.6 进 Trinity 身份 sub-sizar——靠学院补助 + 服侍贵族学生倒夜壶换饭吃。母亲完全有钱供我，只给 10 英镑/年。母子关系冷淡的证据。',
        en: '1646, age 3 — my mother remarried Barnabas Smith, a 63-year-old wealthy rector. Smith did not want me. Hannah left me with my grandmother Margery Ayscough in Woolsthorpe and moved into Smith\'s house, where she had three more children.\n\nFrank Manuel 1968, A Portrait of Isaac Newton ch. 9, reads my life psychoanalytically: lifelong paranoia, vengefulness, lifelong celibacy, lethal feuds with Hooke, Leibniz, Flamsteed — all from being abandoned at three. Manuel\'s framework is 1960s; modern historians do not all accept the chain. But at 19 I wrote in my own notebook a list of sins, including: "Threatening my father and mother Smith to burne them and the house over them." That sentence is mine, not a later guess.\n\n1659 Smith died and Hannah pulled me back to farm at 16. I failed: cattle wandered while I read. My uncle William Ayscough, Cambridge clergyman, persuaded her to send me to Cambridge. June 1661, Trinity College as a sub-sizar — charity student emptying chamber pots for wealthy classmates. Mother could have paid full fees; she sent me 10 pounds a year. Evidence of the coldness.',
      },
      deliverGoal: 'N2 1646 母亲改嫁 + Smith 不要我 + 外婆养 + Manuel 1968 paranoid careful framing + 19 岁烧母亲笔记自证 + 1659 务农失败 + 1661 Trinity sub-sizar',
      engagementHook: '我 19 岁笔记本自己写「想烧死继父跟母亲」——不是后人猜的，是我自己写的。你怎么读「自我承认 vs 后世解读」的差距？',
      expectsRealAnswer: false,
    },
    {
      id: 'newton-n3',
      type: 'narrative',
      content: {
        cn: '⭐ 1665-1666 我 22-23 岁——anni mirabiles（拉丁「奇迹岁月」）。1665 夏 Great Plague 爆发，伦敦 1/4 人口死，Cambridge 关校。我回 Woolsthorpe 老家。18 个月一个人没指导，4 个突破：calculus（我叫 fluxions，没发表）；Theory of Colors 棱镜证白光合成；引力反平方律雏形；切线方法 + 级数展开。\n\n苹果故事——careful framing 三层红旗。来源 William Stukeley 1726 跟 84 岁的我聊天，1752 写进《Memoirs》。红旗 1：来源是我 84 岁回忆 22 岁，60 年后我已是国家英雄，有动机自我神话化。红旗 2：现存 Cambridge UL + Trinity 1665-1666 笔记本里没有「苹果」这个词。红旗 3：Westfall 1980 ch. 4 + Hall 1962 reconstruct 显示我当时算的月球加速度跟苹果比例差 10-20%（用了不准的旧地球半径），范围依赖 reconstruction 不是单一数字。我自己 1666 暂时放弃这想法，20 年后用 Picard 1671 重测半径才算对。\n\nWhig 神话：「苹果掉下，灵感闪光，万有引力诞生」。真相：22 岁雏形 + 18 年闷头算 + 41 岁 Halley 推动才对外讲。',
        en: '⭐ 1665-1666, ages 22-23 — anni mirabiles, "miracle years." Summer 1665 the Great Plague hit London — a quarter of the city died, Cambridge shut. I went home to Woolsthorpe. Over 18 months alone, four breakthroughs: calculus (I called it fluxions, never published); the prism proving white light is composite; the inverse-square gravity in draft; tangent methods and series expansions.\n\nThe apple story — three red flags. Source: William Stukeley talked with me at 84 in 1726 and wrote it into his 1752 Memoirs. Flag 1: source is me at 84 recalling age 22, 60 years on, already a national hero with strong incentive to self-mythologize. Flag 2: no Cambridge UL or Trinity 1665-1666 notebook contains the word "apple." Flag 3: Westfall 1980 ch. 4 and Hall 1962 reconstruct that my 1665 lunar-vs-apple ratio missed by roughly 10-20% (out-of-date Earth radius); the range is reconstruction-dependent, not a single number. I shelved it in 1666 and only got it to fit 20 years later, after Picard\'s 1671 re-measurement.\n\nThe Whig myth: "apple falls, insight strikes, universal gravitation born." The truth: a draft at 22, 18 silent years, then Halley pushing me at 41.',
      },
      deliverGoal: 'N3 ⭐ 1665-1666 anni mirabiles 22-23 + 4 突破 + 苹果 Stukeley 1752 三红旗 careful framing + 月球加速度 10-20% Westfall/Hall reconstruct hedge + 反 Whig',
      engagementHook: '苹果故事来源是我 84 岁回忆 22 岁的事——60 年后我已是国家英雄。你信这种「自我回忆 + 神话化动机」的故事吗？',
      expectsRealAnswer: false,
    },
    {
      id: 'newton-n4',
      type: 'narrative',
      content: {
        cn: '1668 我自己磨镜片造了第一台 reflecting telescope——用凹面镜避开 chromatic aberration（色差）。1671 寄一台到 Royal Society，全场惊呼。\n\n1672.1.11 我被选入 Royal Society。2.6 寄第一篇正式论文「A New Theory about Light and Colours」——棱镜实验证明白光是合成。2.15 Robert Hooke 写「Considerations」反驳，说颜色是介质改变光波形（Hooke 是 wave 理论）。Hooke 语气还算客气，我觉得被人格攻击。3 个月内我写 4 封怒信给 Oldenburg 威胁退会。1673.3 写：「I desire that you will procure that I may be put out」。Oldenburg 安抚下来。从此我把所有想法压住 30 年不发表光学完整版。\n\n1675.12 第二轮——我寄「Hypothesis Explaining the Properties of Light」没署名，Hooke 又跳出来说「这都是我以前讲过的」（1665《Micrographia》波动论）。\n\n1675.4 Charles II 给 Lucasian Chair 颁永久 royal dispensation——不必 take holy orders。Iliffe 2017 ch. 5 论证我是直接 lobbyist。否则我要么放弃教席，要么宣誓信 Trinity（作伪证）：1689 Toleration Act 之前 Arianism 仍是刑事罪。\n\nHooke 战只是序幕。这场仗后来打了 30 年到 1703 Hooke 死才停。',
        en: '1668 I ground mirrors and built the first reflecting telescope — concave mirror, no chromatic aberration. 1671 sent one to the Royal Society. The room gasped.\n\nJanuary 11, 1672, elected to the Royal Society. February 6, my first formal paper, "A New Theory about Light and Colours" — the prism proved white light is composite. February 15, Robert Hooke wrote "Considerations" against it (Hooke was a wave theorist). Hooke\'s tone was polite. I read it as a personal attack. Within three months I wrote four furious letters to Oldenburg threatening to resign. March 1673: "I desire that you will procure that I may be put out." Oldenburg talked me down. From then on I held my full optical work back for 30 years.\n\nDecember 1675, round two. I sent "Hypothesis Explaining the Properties of Light" anonymously; Hooke jumped in: "I said all this already" (his 1665 Micrographia wave theory).\n\nApril 1675, Charles II issued a permanent royal dispensation for the Lucasian Chair — its holder need not take holy orders. Iliffe 2017 ch. 5 argues I lobbied directly. Without it I had to give up the chair or swear belief in the Trinity (perjury): before the 1689 Toleration Act, Arianism was a criminal offense.\n\nThe Hooke battles were prelude. The feud ran 30 years, ending only when Hooke died in 1703.',
      },
      deliverGoal: 'N4 1668 reflector + 1672.1.11 RS 入会 + 1672.2 Hooke Letter on Light 攻击 + 1675-76 第二轮 + 1675.4 Charles II Lucasian dispensation Iliffe 2017 lobbyist',
      engagementHook: 'Hooke 1672.2 写一篇技术反驳——我读成人格攻击，3 个月写 4 封怒信。你怎么读 technical critique 跟 personal attack 的边界？',
      expectsRealAnswer: false,
    },
    {
      id: 'newton-n5',
      type: 'narrative',
      content: {
        cn: '⭐ 1670s 起 25 年——~30 到 ~52 岁——我私下做的事比《Principia》多得多。\n\nAlchemy：Trinity 后院搭炉子烧 + 蒸馏 + 升华金属。现存 Newton alchemy 笔记 ~1,000,000 字（Indiana University Newton Project 全部扫描）。我研究 14c George Ripley + 17c「Eirenaeus Philalethes」（化名，今认为 George Starkey），用「green lion」「Mercury of the Philosophers」记录实验找 Philosopher\'s Stone。\n\n词源链：英文「elixir」← 中世纪拉丁 ← 阿拉伯「al-iksīr الإكسير」← 古希腊 xērion。8-9c Baghdad 化学之父 Jabir ibn Hayyan（750-815，跟 al-Khwarizmi 同代）写过这词。我 1670s 后院炉子边的笔记 270 处「elixir」——直接接到 Abbasid 巴格达学者那一代。Islamic Rise + Scientific Revolution 是同一条 800 年知识链。\n\n神学：现存 ~3,000,000 字总，神学约 ~1,300,000 字——比《Principia》(~500,000 字) 长。主题 Arianism：4c Arius 提出的反三位一体异端。325 Council of Nicaea 定为异端。我读 ~1,000,000 字早期教父著作得出结论：Trinity 是 4c Athanasius 派伪造的。\n\n公私分裂：私下信 Arian，公开装 Anglican 正统。1936.7.13-14 Sotheby\'s 拍 Portsmouth 家族手稿——Keynes 拍下 38 lots ~50%。Keynes 1947 演讲：「He was not the first of the age of reason. He was the last of the magicians」。',
        en: '⭐ From the 1670s onward, 25 years — roughly age 30 to 52 — what I did privately dwarfs the Principia.\n\nAlchemy: a furnace behind Trinity. About 1,000,000 surviving words of alchemical notes (Indiana University Newton Project has scanned them). I read 14th-century Ripley and the 17th-century pseudonymous "Eirenaeus Philalethes" (now believed to be George Starkey), using "green lion" and "Mercury of the Philosophers" to log Philosopher\'s Stone hunts.\n\nEtymological chain: English "elixir" — medieval Latin — Arabic al-iksīr — older Greek xērion. The 8th-9th century Baghdad father of chemistry Jabir ibn Hayyan (750-815, contemporary of al-Khwarizmi) used it. The word appears 270 times in my 1670s notebooks. A direct line to Abbasid Baghdad scholars. Islamic Rise and Scientific Revolution are one 800-year knowledge chain.\n\nTheology: about 3,000,000 surviving words total, of which roughly 1,300,000 are theological. Far longer than the Principia (~500,000). Subject: Arianism, the 4th-century anti-Trinitarian heresy of Arius of Alexandria. Condemned at Nicaea 325. I read about 1,000,000 words of patristic literature and concluded the Trinity was a 4th-century Athanasian forgery.\n\nThe split: privately Arian, publicly Anglican. July 13-14, 1936, Sotheby\'s auctioned my heirs\' Portsmouth manuscripts. Keynes bought 38 lots, half. In a 1947 lecture: "He was not the first of the age of reason. He was the last of the magicians."',
      },
      deliverGoal: 'N5 ⭐ 1670s-1690s 25 年 alchemy 1.3M 字 + Philosopher\'s Stone + elixir ← al-iksir ← Jabir ibn Hayyan cross-Topic + Arianism + 1936 Sotheby\'s Keynes 拍 + Keynes 1947',
      engagementHook: 'Keynes 1947 说我「不是理性时代第一人——是最后的魔法师」。这句话颠覆了你对「现代科学 = 理性」的定义吗？',
      expectsRealAnswer: false,
    },
    {
      id: 'newton-n6',
      type: 'narrative',
      content: {
        cn: '1684.1 London 咖啡馆，Halley + Hooke + Wren 讨论：「假设引力按反平方律，行星轨道是什么形状？」Hooke 吹牛能证椭圆但拿不出证明。Halley 算几个月失败。\n\n1684.8 Halley 第二次访 Cambridge 找我。De Moivre 1727 转述对话：Halley「Mr. Newton, what do you think the curve...」我「An ellipse」。Halley「How do you know it?」我「Why, I have calculated it」。我在堆乱的纸里找不到，答应「重新算」。18 个月后 1685.11 我寄 De Motu 9 页给 Halley——反平方律 + 椭圆轨道证明。\n\n1685.1-1687.4 18 个月强力工作。Book 2「motion in resistive media」直接建立在 1644 Mersenne 转手的 Pascal 流体力学结论上：1644 春 Mersenne 在 Paris Place Royale 修道院 cell 把 Torricelli 1643 水银柱实验讲给 16 岁 Pascal——Pascal 4 年后 Puy-de-Dôme 实验时 Mersenne 已死 18 天。Boyle 1662 复制扩展。Mersenne 死后 39 年的工作链直接喂进我 1687 Book 2。\n\n1685.6 Halley 自费支付印刷。Royal Society 没钱：上一年（1685）他们花光出版预算印 Willughby + Ray《De Historia Piscium》（鱼类志），卖不掉学会破产，连 Hooke 工资都付不出，改给他鱼书库存抵账。Halley 30 岁中等收入（父亲 1684 死留 ~£100/年），自己掏 ~£100-200 印 Principia——约一年收入。\n\n印刷术 1455 Gutenberg → 1543 Copernicus 死前出版可行 → 1685 Halley 自费印 ~250-400 本。230 年物质基础设施链。',
        en: 'January 1684, a London coffeehouse. Halley, Hooke, Wren: "Given an inverse-square law, what is the planetary orbit?" Hooke claims he can prove an ellipse but produces nothing. Halley spends months and fails.\n\nAugust 1684, Halley\'s second Cambridge visit. De Moivre, 1727, recorded the dialogue: Halley — "what would the curve be...?" Me — "An ellipse." Halley — "How do you know?" Me — "Why, I have calculated it." I rummaged, found nothing, promised "I shall calculate it again." Eighteen months later, November 1685, I sent Halley nine pages of De Motu — inverse-square law and elliptical orbit proven.\n\nJanuary 1685 to April 1687, 18 months of intense work. Book 2, "motion in resistive media," builds directly on Mersenne\'s relayed Pascal fluid mechanics. Spring 1644, Mersenne in his Place Royale convent cell relayed Torricelli\'s 1643 mercury-column to a 16-year-old Pascal. When Pascal ran the Puy-de-Dôme experiment four years later, Mersenne had been dead 18 days. Boyle replicated 1662. The chain ran 39 years past Mersenne\'s death and emptied into my Book 2.\n\nJune 1685, Halley paid for printing himself. The Royal Society was broke: the year before they spent the publication budget on Willughby and Ray\'s De Historia Piscium ("History of Fishes"), it failed, and they paid Hooke in fish-book stock. Halley at 30 had middling income (father died 1684 leaving ~£100/year), and his ~£100-200 to print 250-400 copies was about a year\'s pay.\n\nGutenberg 1455 — printing made Copernicus\' 1543 deathbed publication viable — Halley\'s 1685 self-funded Principia. One 230-year material chain.',
      },
      deliverGoal: 'N6 1684.1 咖啡馆 + 1684.8 Halley 对话 + 1685-87 18 月 + 1644 Mersenne→Pascal→Newton 流体力学链 cross-lens micro-detail #1 + Halley 自费印 (鱼书破产) + 印刷术 cross-Topic',
      engagementHook: 'Halley 30 岁中等收入自费印 Principia——花掉一年收入。如果他没那么做，《Principia》会出版吗？',
      expectsRealAnswer: false,
    },
    {
      id: 'newton-n7',
      type: 'narrative',
      content: {
        cn: '⭐ 1687.7.5《Philosophiæ Naturalis Principia Mathematica》出版。3 卷拉丁文 ~510 页 ~250-400 本。\n\n反 Whig 关键：用几何，不用微积分。我自己 22 岁就发明微积分，但《Principia》全部用 Euclid 风格几何证明。两个原因：怕 Hooke 抢先（微积分没发表，用微积分 Hooke 会说「这是新数学，看不懂，不算证明」）；哲学保守（私下笔记写过几何是「ancient and venerable」古老而尊贵的论证形式）。结果 18c 欧洲数学家花 ~50 年才把《Principia》几何证明翻译回微积分形式。我自己藏了一手。\n\n微积分本身建立在 al-Khwarizmi 825《Kitab al-Jabr》的 algebra 符号传统上：英文 algebra ← 中世纪拉丁 ← 阿拉伯 al-jabr。没有 825 Baghdad，没有 1665 我的 fluxions。一条 800 年知识链。Erasmus 1517 给 Luther 的信启动 Reformation；Mersenne 1640 给 Galileo + Descartes 的信组成 Scientific Revolution 传播层；Royal Society 1660 institutional 接班。\n\n1687.7.5 同日时间不齐切片三 lens：Lens 1 我 44 岁 Cambridge Trinity 拿到 Halley 第一本。Lens 2 Mersenne 死 39 年但 Oldenburg 1665 创办的 Philosophical Transactions 那期立刻 review《Principia》——43 年前那一夜 ripple 到达 Cambridge。Lens 3 Maria Winckelmann 17 岁在 Saxony Sommerfeld 农夫天文学家 Christoph Arnold 家做学徒，13 年后她到 Berlin，23 年后她发现彗星，institution 都还要不承认她。\n\nLocke / Huygens / Leibniz 全读。Leibniz 1684 已发表独立微积分。Newton-Leibniz 优先权之战种子从这里埋下。',
        en: '⭐ July 5, 1687: Philosophiæ Naturalis Principia Mathematica published. Three Latin volumes, about 510 pages, 250-400 copies.\n\nThe anti-Whig core: geometry, not calculus. I had invented calculus at 22, but every Principia proof is Euclidean geometry. Two reasons: fear of Hooke (unpublished calculus would let Hooke say "new mathematics, I cannot read it, the proof does not count") and philosophical conservatism (my notes call geometry "ancient and venerable"). Cost: 18th-century mathematicians took about 50 years to translate the geometric proofs back into calculus. I held one hand back.\n\nThe calculus rests on al-Khwarizmi\'s 825 Kitab al-Jabr — algebra. English "algebra" — medieval Latin — Arabic al-jabr. No 825 Baghdad, no my 1665 fluxions. One 800-year chain. Erasmus\' 1517 letter to Luther started the Reformation; Mersenne\'s 1640s letters to Galileo and Descartes built the Scientific Revolution\'s transmission layer; the 1660 Royal Society institutionalized it.\n\nJuly 5, 1687, cross-lens slice. Lens 1: me at 44 in Trinity, holding Halley\'s first copy. Lens 2: Mersenne 39 years dead, but Oldenburg\'s Philosophical Transactions reviews the Principia in the next issue — a ripple from one Paris evening 43 years earlier reaching Cambridge. Lens 3: Maria Winckelmann, 17 in Saxon Sommerfeld, apprentice in the home of the peasant astronomer Christoph Arnold. 13 years before she reaches Berlin, 23 before she discovers a comet, and the institution still will not accept her.\n\nLocke, Huygens, Leibniz all read it. Leibniz had published his independent calculus in 1684. The seed of the Newton-Leibniz priority war is planted on this day.',
      },
      deliverGoal: 'N7 ⭐ 1687.7.5 出版 + 几何不用微积分 反 Whig + algebra ← al-Khwarizmi 825 cross-Topic + 三 lens 时间不齐切片 cross-lens #2 + Erasmus → Mersenne → RS',
      engagementHook: '我自己 22 岁发明微积分，《Principia》却全用几何——藏了一手。这是「智慧」还是「怕被超越」？',
      expectsRealAnswer: false,
    },
    {
      id: 'newton-n8',
      type: 'narrative',
      content: {
        cn: '1689 我 47 岁，光荣革命后被 Cambridge 选为 Convention Parliament 议员（1689.1-1690.2）。1687 James II 下令 Cambridge 给 Benedictine 修士 Alban Francis 颁学位但不要求宣誓 Anglican，Cambridge 集体抗议——我是 8 个抗议代表之一出庭。议会 13 个月我只发言一次——请求关窗（because he was cold，Westfall 1980 引同时代记录）。\n\n1693 The Black Year 50 岁突发癫狂期 ⭐——Lens 1 中段 critical。\n\n1693 春-夏几件事压上来：Fatio de Duillier（瑞士数学家，比我小 22 岁，60+ 封通信极密切私交）1693.5 跟我中断；母亲 Hannah 1689.6 死（4 年延迟 grief，我 3 岁被她抛弃，1689 守了她最后几周）；25 年 alchemy 大量水银接触。\n\n1693.9.13 我写信 Samuel Pepys（Royal Society President）：「I beg of you to suffer me to forget you, and to forget all my friends. I have not been able to sleep these twelvemonth, nor have I my former consistency of mind」。1693.9.16 写信 John Locke——明显 paranoid delusion：「being of opinion that you endeavoured to embroil me with women」。Locke 完全没做过此事。\n\n病因学界 spectrum：19c Brewster 1855 推 mercury poisoning（25 年 alchemy 水银暴露）。20-21c Manuel 1968 + Westfall 1980 + Iliffe 2017 倾向 emotional collapse（Fatio + 母亲 + Arian 双重生活 chronic anxiety）。1979 Spargo & Pounds 头发样本 mercury/lead/arsenic 显著高于 baseline，但样本年代是 1727 不是 1693，不能直接证。最 honest framing：multifactorial。1694 春恢复，1696 Mint 后 30 年没复发。',
        en: '1689, age 47, post-Glorious Revolution — Cambridge elected me to the Convention Parliament (January 1689 to February 1690). In 1687 James II had ordered Cambridge to grant a degree to the Benedictine monk Alban Francis without an Anglican oath; Cambridge refused, and I was one of eight delegates sent to argue. In Parliament for 13 months I spoke once — to request a closed window (because he was cold; Westfall 1980 cites the contemporary record).\n\n1693, the Black Year, age 50, the acute breakdown. ⭐ Critical Lens 1 middle.\n\nThings piled up that spring and summer. Fatio de Duillier (Swiss mathematician 22 years my junior, 60+ letters of intense friendship) cut contact in May 1693. My mother Hannah had died June 1689 — a four-year delayed grief; she abandoned me at three, and when she died I sat with her last weeks. Twenty-five years of alchemy meant heavy mercury exposure.\n\nSeptember 13, 1693, I wrote to Samuel Pepys (Royal Society President): "I beg of you to suffer me to forget you, and to forget all my friends. I have not been able to sleep these twelvemonth, nor have I my former consistency of mind." September 16, I wrote to John Locke — clear paranoid delusion: "being of opinion that you endeavoured to embroil me with women." Locke had done nothing of the kind.\n\nScholarly spectrum on cause. 19th century: Brewster 1855 blamed mercury from alchemy. 20th-21st: Manuel 1968, Westfall 1980, Iliffe 2017 lean emotional collapse (Fatio, delayed maternal grief, chronic Arian double-life anxiety). Spargo and Pounds 1979 found elevated mercury, lead, arsenic in my preserved hair, but the samples date to 1727 not 1693; mercury cannot be ruled out, but cannot be proven for the Black Year. Honest framing: multifactorial. Recovered by spring 1694; Mint work from 1696 shows 30 years with no relapse.',
      },
      deliverGoal: 'N8 1689 Convention Parliament + 关窗一次 + 1693 Black Year 50 岁 ⭐ + Fatio + 母亲延迟 grief + Pepys + Locke 信原文 + 19c mercury vs 21c emotional collapse hedge spectrum + Spargo & Pounds 1979',
      engagementHook: '我 50 岁给 Locke 写信指控他「想用女人陷害我」——明显 paranoid delusion。「不会犯错的天才」 vs 「中年崩溃」——你怎么读公众形象 vs 真实状态的差距？',
      expectsRealAnswer: false,
    },
    {
      id: 'newton-n9',
      type: 'narrative',
      content: {
        cn: '1696.4 我 53 岁，离 Cambridge 移居 London 任 Royal Mint Warden。1699.12 升 Master of the Mint，到 1727 死，31 年。\n\n三个 layer：表面 Charles Montagu（财政大臣，我 Cambridge 老友）1696 推动 Great Recoinage——硬币因 clipping 严重贬值，政府要全部回收重铸。中层 Black Year 后 Cambridge 让我觉得 isolating，需要换环境。深层薪资：Mint Warden 年薪 £400，Master 年薪 £1500+，Cambridge Lucasian 教授只 £100。\n\ncareful framing：Mint Warden 法定职责包括起诉 counterfeiters + clippers。我不是「业余追踪犯人」——我是 chief prosecutor。\n\nWestfall 1980 ch. 12 + Craig 1946《Newton at the Mint》整理 Mint archives + UK National Archives：1697-1700 三年我起诉 28+ 名伪币犯，全部判死刑（绞架 + 内脏剖出焚烧——17c 英国对 high treason counterfeiting 标准刑罚）。最有名 William Chaloner 1699.3.22 在 Tyburn 被绞死。Chaloner 曾两次给议会写信 propose Mint 改革（其实是想偷我位置）。我花 18 个月秘密 building case——化装去 London 酒馆收集证据，审问 14 名证人。亲自审问 200+ 名犯人 / 证人。\n\nLevenson 2009《Newton and the Counterfeiter》：写《Principia》的同一个我 7 年后亲手送 28+ 人上绞架。这不是「污点」也不是「转型」——是 17c 末英国 state-building 中科学家 ↔ 公务员 ↔ 司法的 tight coupling。我自己不觉得有 contradiction，Mint 工作跟 Principia 数学一样需要 patient detective work。',
        en: 'April 1696, age 53, I left Cambridge for London as Warden of the Royal Mint. December 1699, promoted to Master, where I stayed until my death in 1727 — 31 years.\n\nThree layers. Surface: Charles Montagu (Chancellor of the Exchequer and my Cambridge friend) was pushing the Great Recoinage in 1696, because clipping had badly debased English coin. Middle: post-Black Year, Cambridge felt isolating; I needed a change. Deep: Warden\'s salary £400/year, Master\'s £1,500+. The Lucasian chair paid £100.\n\nCareful framing: as Warden, prosecuting counterfeiters and clippers was my statutory duty. Not amateur sleuthing. I was chief prosecutor.\n\nWestfall 1980 ch. 12 and John Craig\'s 1946 Newton at the Mint, working through the Mint archives at the Royal Mint Museum and the UK National Archives: in three years (1697-1700) I prosecuted 28+ counterfeiters, all sentenced to death (hanging, then disembowelment and burning — the 17th-century English penalty for counterfeiting as high treason). The most famous, William Chaloner, hanged at Tyburn on March 22, 1699. Chaloner had twice written Parliament proposing "Mint reforms" (he wanted my job). I spent 18 months building the case in secret — going to London taverns in disguise, working up 14 witnesses. I personally interrogated 200+ suspects.\n\nThomas Levenson, Newton and the Counterfeiter (2009): the man who wrote the Principia sent 28+ people to the gallows seven years later. Not a "stain" and not a "career change." Late-17th-century English state-building tightly coupled scientist, civil servant, and judiciary. I felt no contradiction — Mint work, like Principia mathematics, needed patient detective work.',
      },
      deliverGoal: 'N9 1696.4 Mint Warden 53 岁 + 1699 Master + 三 layer + 1697-1700 28+ 伪币犯绞架 (Westfall ch. 12 + Craig 1946 + Levenson 2009) + Chaloner 1699.3.22 Tyburn',
      engagementHook: '写《Principia》的我 7 年后亲手送 28+ 人上绞架。这是「污点」、「转型」、还是「同一种 patient detective work 在不同领域」？',
      expectsRealAnswer: false,
    },
    {
      id: 'newton-n10',
      type: 'narrative',
      content: {
        cn: '⭐ 1703.3.3 Robert Hooke 死。8 个月后 1703.11 我 60 岁当选 Royal Society President——24 年史上最长任期。1705.4.16 Queen Anne 在 Cambridge Trinity 给我封爵。1710 RS 搬新址 Crane Court 时 Hooke 唯一 portrait「丢失」。Lisa Jardine 2003 没 smoking gun 说我销毁，但圈内共识是我至少 acquiesced（默许）。Hooke 至今没任何 confirmed portrait 流传。\n\n1710 同年 Cambridge 开除 William Whiston——我的 protégé，1701 接我 Lucasian Chair——因 Arian 异端被开除。反讽：我自己秘密信 Arian 30+ 年但因为我是 Newton，Cambridge 装不知道。Whiston 1710 写信问我求救，我装聋作哑（Iliffe 2017 ch. 7）。\n\n1710-1711 institutional moment 三 lens micro-detail #3：1711.1.18 Berlin Academy Council 用德文「Frauenzimmer 不应任职」拒绝 Maria Kirch（Gottfried 1710.7.25 死后 Maria 申请接任）。同年 Cambridge 用「Arian 异端」开除 Whiston。两 institution 用不同理由开除两种不可见信仰但同一种 logic：「怕开先例，怕外界 perception」。Maria 1711.4「变的不是我的手，是我的身份」。\n\n1712-1717 Leibniz 微积分 priority 战。1665-66 我 23 岁发明 fluxions 没出版。1675-76 Leibniz Paris 独立发明用 dx/dy。1684 Leibniz 在《Acta Eruditorum》发表——比我早 9 年公开。1712.3 Royal Society 成立 priority committee 11 人，全部我自己挑（Halley/Machin/Burnet）。Leibniz 没被通知没机会答辩。我亲手写 70%《Commercium Epistolicum》文字但报告以「Royal Society 集体决议」名义发布。1715 那篇 anonymous review 是我自己写的（Smith 2004 + Westfall 1980 ch. 14 现存档案有亲笔手稿）。\n\n1676.2.5 我给 Hooke 信「If I have seen further it is by standing on the shoulders of Giants」——19c humility 典范读法。21c George Smith 2002 + Iliffe 2017 + Gleick 2003 偏 sarcasm reading（Hooke 矮小驼背 + 25 年记仇中段）。Westfall 1980 中立。最 honest：sarcasm 是 21c 主流推测，不是 1676 信里 explicit 写出的事实。\n\nGalileo 1633 软禁《Discorsi》跟 Su Shi 1080 黄州被贬《赤壁赋》同 pattern——perpetrator-actor 系统打压 lonely-mediator 中产文学产出最高作品。',
        en: '⭐ March 3, 1703, Robert Hooke died. November 1703, age 60, I was elected Royal Society President — 24 years, the longest tenure. April 16, 1705, Queen Anne knighted me at Trinity. 1710 the Society moved to Crane Court and Hooke\'s only portrait "vanished." Lisa Jardine 2003 finds no smoking gun pointing to me, but the consensus is at minimum acquiescence. No confirmed portrait of Hooke survives.\n\nSame 1710 Cambridge expelled William Whiston — my protégé, my 1701 Lucasian successor — for Arian heresy. The irony: I had been a secret Arian for over 30 years, and because I was Newton, Cambridge looked the other way. Whiston wrote me asking for help. I went silent (Iliffe 2017 ch. 7).\n\nThe 1710-1711 cross-lens institutional moment, micro-detail #3: January 18, 1711, the Berlin Academy Council refused Maria Kirch in German with "Frauenzimmer would bring little honor" (after Gottfried\'s death July 25, 1710 she had applied to inherit his post). Same year Cambridge expelled Whiston for "Arian heresy." Two institutions, two surface reasons, one logic: "afraid of setting a precedent, afraid of perception." Maria\'s April 1711 letter — "what changed is not my hand but my position."\n\n1712-1717, Leibniz priority war. I invented fluxions 1665-66 at 23 and never published. Leibniz invented his calculus independently in Paris 1675-76 with dx/dy. He published 1684 in Acta Eruditorum — nine years before any public hint from me. March 1712 the Royal Society set up an 11-person priority committee. I picked them all (Halley, Machin, Burnet). Leibniz was not notified and had no chance to reply. I wrote 70% of the Commercium Epistolicum personally, but it issued as "collective verdict." The 1715 anonymous review is in my hand (Smith 2004; Westfall 1980 ch. 14 — surviving manuscripts at the Royal Society archives).\n\nFebruary 5, 1676, I wrote Hooke "If I have seen further it is by standing on the shoulders of Giants." 19th century read humility. 21st century — Smith 2002, Iliffe 2017, Gleick 2003 — leans sarcasm (Hooke was short and hunchbacked; mid-feud). Westfall 1980 stays neutral. Honest framing: sarcasm is the dominant 21st-century reading, not an established 1676 fact.\n\nGalileo\'s 1633 house arrest writing the Discorsi and Su Shi\'s 1080 Huangzhou exile writing the Red Cliff Rhapsody share one pattern — perpetrator-actor systems crushing a lonely-mediator who produces his highest work in confinement.',
      },
      deliverGoal: 'N10 ⭐ 1703 Hooke 死 + 1703.11 RS President + 1705 封爵 + 1710 Hooke portrait 消失 (Jardine 2003) + 1710 Whiston 开除 + 1711.1.18 Berlin 拒 Maria cross-lens #3 + 1712-1717 Leibniz 暗箱 (Smith 2004) + 巨人肩上 hedge + Galileo 1633 vs Su Shi 1080 cross-Topic',
      engagementHook: '我 70 岁、封爵、RS President、Mint Master——不需要这场胜利。但还是用 institutional power 暗中碾压 70 岁的 Leibniz。你怎么读「权力达到顶点反而更暴力」？',
      expectsRealAnswer: false,
    },
    {
      id: 'newton-n11',
      type: 'synthesis',
      content: {
        cn: '我 1727.3.20 死，84 岁，London Kensington 家中，膀胱结石（3.18 还参加 Royal Society 会议）。Westminster Abbey 国葬——第一个 scientist 被 Westminster Abbey 国葬。\n\nVoltaire 1727.3 在 London 流亡（careful framing：他自己《Lettres philosophiques》1734 没有第一人称 "I saw" 描述，「亲眼见」是后世推测，不是 Voltaire 自述）。但他后来 1734 + 1738《Éléments de la philosophie de Newton》把我包装成「理性时代预言家」，启动整个法国 Enlightenment 对 Newton 的崇拜。Voltaire 笔下的我是 idealized 版本——完全没提 alchemy / Arianism / Mint 28 绞架 / Leibniz priority 战。这是 historical reception 的 selective amnesia——一个被记成神。\n\n两边同样真：左边极致 system-builder。1687《Principia》统一 Kepler 椭圆 + Galileo 落体 + Mersenne 通信网 + Descartes 几何 + Pascal 流体 + Huygens 钟摆。一条 800 年知识链（al-Khwarizmi 825 algebra → 我 1665 fluxions → 1687 Principia）。\n\n右边系统性暴力执行者。25 年 alchemy + 130 万字 Arian 异端 + Mint 28+ 绞架 + Hooke portrait 消失 + 1712-1717 Leibniz 暗箱 + 1715 自评匿名 review。Hooke 30 年记仇 + Leibniz 70 岁碾压 + Flamsteed 强行出版未完成星表（Flamsteed 1715 自己买回 300 本烧掉）。\n\n这两边不是「优点 + 缺点」，是同一套心理在不同领域的表现。\n\n21c 5 个 system-builder + 系统暴力同体样本你身边可能存在：Big Tech CEO（FAANG 创始人级）/ 学校校长（高强度 system 但学生权利受压）/ 政府官员（建制 + 行政暴力）/ 创业者（极致 system + 员工压榨）/ 父母（家庭 system 极致投入 + 子女自主权剥夺）。',
        en: 'I died March 20, 1727, age 84, at Kensington, of bladder stone (March 18 I had still attended a Royal Society meeting). Westminster Abbey state funeral — the first scientist buried there.\n\nVoltaire was in exile in London in March 1727 (careful framing: his 1734 Lettres philosophiques contains no first-person "I saw" — "Voltaire witnessed the funeral" is later inference, not his own claim). But his 1734 Letters and 1738 Éléments de la philosophie de Newton packaged me as the prophet of the Age of Reason and launched the French Enlightenment Newton cult. Voltaire\'s Newton is idealized — not a word on alchemy, Arianism, the 28 Mint hangings, the Leibniz war. The selective amnesia of historical reception — a man remembered as a god.\n\nBoth sides equally true. Left — extreme system-builder. The 1687 Principia unified Kepler\'s ellipses, Galileo\'s fall, Mersenne\'s correspondence, Descartes\' geometry, Pascal\'s fluids, Huygens\' pendulum. An 800-year knowledge chain (al-Khwarizmi\'s 825 algebra, my 1665 fluxions, the 1687 Principia).\n\nRight — perpetrator of systematic violence. 25 years of alchemy. 1.3 million words of Arian heresy. 28+ counterfeiters hanged. Hooke\'s only portrait gone. The 1712-1717 Leibniz star chamber. The 1715 anonymous self-review. A 30-year grudge against Hooke. Crushing Leibniz at 70. Forcing Flamsteed\'s incomplete star catalog into print (Flamsteed bought back and burned 300 of 400 in 1715).\n\nThe two sides are not "strengths and weaknesses." Same psychology across different domains.\n\nFive 21st-century system-builder-and-systematic-violence samples likely live near you: a Big Tech CEO (FAANG founder tier); a school principal (extreme system, student rights compressed); a government official (institutional and administrative violence); a startup founder (extreme system, exploitation of employees); a parent (extreme household system, child autonomy stripped).',
      },
      deliverGoal: 'N11 expectsRealAnswer:true — 1727.3.20 死 Westminster Abbey 国葬 + Voltaire selective amnesia (1727 在 London careful framing) + 双 view 极致 system-builder vs 系统性暴力执行者 + 21c 5 system-builder samples',
      engagementHook: '21c 5 个 system-builder + 系统暴力同体样本：Big Tech CEO / 学校校长 / 政府官员 / 创业者 / 父母——你身边「极致 system + 系统暴力 + 同一个人」是谁？',
      expectsRealAnswer: true,
    },
    {
      id: 'newton-n12',
      type: 'synthesis',
      content: {
        cn: '最后——跨文化 6 个 perpetrator-actor 1500 年对照——同一种角色在不同文明里。\n\n1. Genghis Khan（1206 蒙古高原 Onon 河源头 Kurultai 称汗）——草原系统构建者：Yasa 大札撒 + tumen 万户军制 + Yam 驿站 + 宗教 toleration（13c 世界独有）。同一个人 1219-1221 西征屠 Bukhara/Samarkand/Urgench/Merv 几百万人。\n\n2. 宋徽宗（1100-1126 北宋）——艺术皇帝：瘦金体 + 院体画 + 文人画——文化高峰。同一个人主导北宋政治崩溃 + 1126 靖康之变金兵掳二帝。Su Shi 1080 黄州被贬《赤壁赋》是这套政治打压系统的产物（cross-Topic Tang-Song）。\n\n3. Mansa Musa（1324 Mali 朝圣）——14c 非洲 wealth projector：跨撒哈拉黄金贸易 + Cairo 经济震荡 + Timbuktu 大学。同一个人 12,000 enslaved 8,000 km 跨撒哈拉奴贩。\n\n4. Lorenzo de\' Medici（15c Florence）——文艺复兴金主：Botticelli + Michelangelo + Leonardo + 新柏拉图主义学院。同一个人 1478 Pazzi 阴谋后报复 + 共和国 facade 下家族独裁。\n\n5. Justinian（6c Byzantine）——重建罗马帝国：Hagia Sophia + Justinian Code + Belisarius 西征。同一个人 532 Nika 暴动屠 30,000 人。\n\n6. 我，Isaac Newton（1687 Cambridge Trinity）——极致 system-builder：《Principia》统一 60 年欧洲数学物理 + 800 年 algebra 知识链。同一个我 25 年 alchemy 异端 + Mint 28 绞架 + Hooke 30 年记仇 + Leibniz 70 岁碾压。\n\n6 个人 6 种文明 1500 年——但同一个 pattern：极致系统构建 + 系统性暴力 + 同一个人。这不是「都是坏人」，是 perpetrator-actor 这个角色在所有文明里都存在，而且经常成就跟暴力同体。\n\n21c AP DBQ 训练你 hold contradictions——同时看到光跟影，不二元化。我 1687.7.5 出版《Principia》也 1697-1700 派 28 人上绞架。Voltaire 笔下 idealized Newton 是真的，Westminster Abbey 国葬是真的，Mint 28 绞架也是真的。两件事是同一个我。',
        en: 'Last — six cross-cultural perpetrator-actors over 1,500 years. The same role across civilizations.\n\n1. Genghis Khan (1206 Kurultai at the source of the Onon) — steppe system-builder: Yasa code, tumen army, Yam relay, religious toleration unique to the 13th-century world. The same man\'s 1219-1221 western campaign sacked Bukhara, Samarkand, Urgench, Merv — millions.\n\n2. Emperor Huizong (1100-1126 Northern Song) — artist-emperor: slender-gold calligraphy, court academy painting, literati art — a cultural peak. The same man presided over the Northern Song\'s collapse and the 1126 Jingkang catastrophe in which the Jin captured two emperors. Su Shi\'s 1080 Huangzhou exile and Red Cliff Rhapsody were products of that suppression system (cross-Topic Tang-Song).\n\n3. Mansa Musa (1324 Mali hajj) — 14th-century African wealth projector: trans-Saharan gold trade, Cairo economic shock, Timbuktu university. The same man marched 12,000 enslaved people 8,000 km across the Sahara.\n\n4. Lorenzo de\' Medici (15th-century Florence) — Renaissance patron: Botticelli, Michelangelo, Leonardo, Neo-Platonic academy. The same man\'s reprisals after the 1478 Pazzi conspiracy, and his de facto family dictatorship under a republican facade.\n\n5. Justinian (6th-century Byzantium) — restorer of the Roman empire: Hagia Sophia, Justinian Code, Belisarius. The same man ordered the 532 Nika riot massacre of 30,000.\n\n6. Me, Isaac Newton (1687 Cambridge Trinity) — extreme system-builder: the Principia unified 60 years of European mathematics and physics, plugged into an 800-year algebra chain. The same me: 25 years of alchemy heresy, 28 Mint hangings, 30 years grudge against Hooke, 70-year-old Leibniz crushed.\n\nSix people, six civilizations, 1,500 years. The pattern is the same: extreme system-building, systematic violence, same person. Not "they were all bad people." The perpetrator-actor role exists in every civilization, and achievement and violence often inhabit one body.\n\n21st-century AP DBQ asks you to hold contradictions — see light and shadow at once — without flattening into binaries. I published the Principia July 5, 1687. I sent 28 men to the gallows between 1697 and 1700. Voltaire\'s idealized Newton is real. The Westminster Abbey funeral is real. The 28 Mint hangings are real. They are the same person.',
      },
      deliverGoal: 'N12 closing meta — 6 perpetrator-actor 跨文化对照 1500 年 (Genghis 1206 / Huizong 1100 / Mansa Musa 1324 / Lorenzo 15c / Justinian 6c / me Newton 1687) + 同 pattern + AP DBQ hold contradictions',
      engagementHook: '6 种文明 1500 年——同一个 pattern (极致系统 + 系统性暴力 + 同一个人)。这是「人性常态」还是「权力结构必然」？你站哪边——为什么？',
      expectsRealAnswer: true,
    },
  ],
};
