// ─── Scientific Revolution · LENS 3: Maria Winkelmann Kirch (receiving-end) ───
//
// Topic: Scientific Revolution 1543-1687 · 科学革命
// AP World 4.5 / 6th Grade World History
//
// Lens 3 设计 (per spec / Sarah audit 7.5/10):
//   - id: 'maria-kirch'
//   - role: 'receiving-end'
//   - perspectiveTag: 'astronomer-denied-Berlin-Academy-seat'
//   - defaultLens: true (受影响者优先 + Phase 1 receiving-end 收官 emotional climax)
//
// 真人 (NOT fictional composite):
//   Maria Margaretha Winckelmann Kirch (1670.2.25-1720.12.29), 50 岁。
//   Saxony Panitzsch 路德派牧师女儿 / 1683 13 岁 Christoph Arnold 学徒 /
//   1692 22 岁嫁 Gottfried Kirch 50 岁 / 1702.4.21 独立发现彗星 /
//   1710 Gottfried 死 / 1711.1.18 Berlin Academy 拒绝 (Frauenzimmer 不应任职) /
//   1712-1714 Krosigk 私人 astronomer / 1714-1716 流亡 Danzig Hevelius 旧观测台
//   (Lens 2 §11.5 cross-lens bridge ⭐) / 1717 回 Berlin 做儿子 Christfried helper /
//   1720.12.29 死 葬 Berlin Sophienkirche.
//   史料 archive 级: Schiebinger 1989 ch. 4 引 Berlin Academy 1711.1.18 Council
//   Minutes 德文原文 + Maria 1711.4 信原文 (Berlin-Brandenburg Academy archives).
//   不需要 fictionalDisclaimer — Maria 是真人.
//
// 跨 lens micro-detail (Sarah audit 锁定):
//   1. 1644 Mersenne→Pascal→Newton 流体力学链 (N6 cross-ref)
//   2. 1687.7.5《Principia》出版当天三 lens 时间不齐切片 (N6) —
//      Newton 44 岁 / Mersenne 死 39 年 / Maria 17 岁 在 Saxony 学 Latin
//   3. 1710-1712 Berlin 拒 Maria + Cambridge 开除 Whiston (N7+N8) —
//      institutional 自我保护同 pattern (Iliffe 2017)
//   4. Hevelius 老观测台 1641 Stellaeburgum (N9) —
//      Lens 2 §11.5 Hevelius bridge / Maria 1714 流亡用同一栋楼
//
// Cross-Topic 6+1 缝合:
//   - Maria 学徒制 (1683) ← Mali Fatima al-Fihri 859 al-Qarawiyyin (N2 — 800 年差)
//   - Reformation 17c 北德路德派女子识字率 ← Reformation Topic (N1)
//   - Hevelius 老观测台 ← Lens 2 §11.5 Mersenne (N9)
//   - 17c 14% 德国 astronomer 是女性 ← Tang-Song Li Qingzhao 12c 词人 (N4)
//   - 「我夫」cultural ban ← Byzantine Theodora N6 (N8 — Maria 1711 信同 pattern)
//   - 跨 6 文明 7 真 + 4 虚 receiving-end 女性 ← 全 Phase 1 收官 (N12)
//
// 严格规则 (per Newton/Mersenne lens-author + 第 12 条):
//   - 不用 *italic* markdown — 外语词 bare + inline gloss
//   - 内嵌引号: 「」(CN) / "..." (EN), 严禁 «...»
//   - em-dash 「——」 ≤ 2 per 段, 0 段 4+ chain (per Crusades 全局 hotfix)
//   - 每 node 350-550 CN chars
//   - expectsRealAnswer 默认 false, 只 N11+N12 设 true
//   - 不需要 fictionalDisclaimer (Maria 是真人)
//   - 7 年级 careful framing
//
// Anti-fab citations:
//   - Schiebinger 1989《The Mind Has No Sex? Women in the Origins of Modern
//     Science》(Harvard) ch. 3-4 pp. 79-101
//   - Margaret Alic 1986《Hypatia's Heritage》(Beacon) ch. 5 pp. 121-150
//   - Marilyn Ogilvie 1986《Women in Science》(MIT) Maria Kirch entry pp. 109-110
//   - Westfall 1980《Never at Rest》(Cambridge) Mint + Royal Society + Leibniz
//   - Iliffe 2017《Priest of Nature》(Oxford) — 1710-1712 institutional 自我保护

// ═══════════════════════════════════════════════════
// LENS 3: Maria Winkelmann Kirch (astronomer-denied-Berlin-Academy-seat)
// ═══════════════════════════════════════════════════

export var mariaKirchLens = {
  id: 'maria-kirch',
  name: 'Maria Winkelmann Kirch',
  nameCn: '玛丽亚·温克尔曼·基尔希',
  role: 'receiving-end',
  perspectiveTag: 'astronomer-denied-Berlin-Academy-seat',
  defaultLens: true,
  description: {
    en: 'You are Maria Margaretha Winckelmann Kirch (25 February 1670 - 29 December 1720), born in the Saxon village of Panitzsch, ten kilometers east of Leipzig, in the Holy Roman Empire. Your father, Matthias Winckelmann, was a Lutheran pastor who taught you Latin before he died in 1683 (you were 13). Your mother died the same year. Your uncle Justinus Toellner, also a Lutheran pastor, raised you. At 13 you were apprenticed to Christoph Arnold, a self-taught peasant astronomer in Sommerfeld, where you lived in his household for nine years (1683-1692), learning Latin, spherical trigonometry, telescope observation, and how to write observation reports. In 1692 at age 22 you married Gottfried Kirch (1639-1710), a 50-year-old astronomer, the man Arnold introduced. From 1692 to 1710 you and Gottfried worked as a dual-pair: he ran the early night, you ran the late night, four children all of whom became astronomers. On 21 April 1702, just past midnight, you independently discovered a comet from the Berlin Academy observatory using Gottfried\'s 4-foot refractor. Gottfried\'s 25 April 1702 letter to Leibniz states plainly that you, his wife, made the discovery, but the Academy announcement listed only Gottfried\'s name. When Gottfried died in 1710 you applied to succeed him as Berlin Academy astronomer. Leibniz, the Academy\'s president, supported you. The Council refused on 18 January 1711 with the German phrase "Frauenzimmer should not be employed as astronomer" (Berlin Academy archives). You were given 100 thaler and three months to leave the observatory apartment. From 1712 to 1714 you worked as private astronomer for the Berlin merchant Krosigk; from 1714 to 1716 you worked at the old Hevelius observatory in Danzig (the same building where Elisabetha Hevelius had run things from 1663 to 1693). In 1717 you returned to Berlin as your 23-year-old son Christfried\'s assistant at the same observatory you had once helped found. You died on 29 December 1720, aged 50, of fever, and were buried at Berlin Sophienkirche. The 21st-century careful framing (Schiebinger 1989, Alic 1986, Ogilvie 1986): your case is not "one woman beaten by one Academy" , it is the structural face of a 17th-century pattern in which 14 percent of German astronomers were women working as wife, sister, or daughter inside dual-pair households, doing the same observations, signing nothing under their own name, and disappearing from the historical record until late-20th-century scholarship pulled them back out of the archives.',
    cn: '你是 Maria Margaretha Winckelmann Kirch（玛丽亚·玛格丽特·温克尔曼·基尔希，1670 年 2 月 25 日 , 1720 年 12 月 29 日），生于神圣罗马帝国 Saxony（萨克森）的 Panitzsch 小村，在 Leipzig 东 10 公里。父亲 Matthias Winckelmann 是路德派牧师（Lutheran pastor），1683 年你 13 岁时父亲死，母亲同年死。叔叔 Justinus Toellner（也是路德派牧师）抚养你，父亲死前已教你 Latin。13 岁那年你被送到 Sommerfeld 跟 Christoph Arnold 当学徒,,他是一个 self-taught peasant astronomer（自学农夫天文学家）。你跟 Arnold 一家同住 9 年（1683-1692），学 Latin、球面三角学、望远镜观测、怎么写观测报告。1692 年 22 岁你嫁给 Gottfried Kirch（1639-1710）50 岁的 Berlin 天文学家,,Arnold 是介绍人。1692 到 1710 年你跟 Gottfried 是 dual-pair（双人工作档）：他守上半夜，你守下半夜，生 4 个孩子全部进入天文。1702 年 4 月 21 日凌晨，你用 Gottfried 的 4 英尺折射式望远镜在 Berlin Academy 观测台独立发现一颗彗星。Gottfried 1702 年 4 月 25 日写信 Leibniz 原文说是「我妻子 Maria」发现的，但 Academy 公告只挂 Gottfried 名。1710 年 Gottfried 死后你申请接任 Berlin Academy astronomer 职位，Leibniz 作为 Academy President 强力支持。但 1711 年 1 月 18 日 Council 否决，理由：「Frauenzimmer 不应任职 astronomer」（Berlin Academy 档案德文原文）。给你 100 thaler + 3 个月内搬出观测台公寓。1712-1714 你在 Berlin 商人 Krosigk 家做私人 astronomer，1714-1716 流亡 Danzig 用 Hevelius 1641 建的旧观测台（Elisabetha Hevelius 1663-1693 在那里工作 30 年）。1717 你 47 岁回 Berlin 做 23 岁儿子 Christfried 的助手,,同一栋观测台你帮忙创建过。1720 年 12 月 29 日你死，50 岁，热病，葬 Berlin Sophienkirche。21 世纪 careful framing（Schiebinger 1989 + Alic 1986 + Ogilvie 1986）：你的 case 不是「一个女人被一个 Academy 打败」,,是 17 世纪一种 structural pattern 的最清楚的脸：17 世纪末德国 astronomer 14% 是女性，几乎全部以 wife / sister / daughter 身份在 dual-pair 家庭里工作，做同样的观测、不署自己名、从历史记录里消失，一直到 20 世纪末学术界才把她们从档案里挖回来。',
  },
  storyboard: [
    {
      id: 'maria-n1',
      type: 'narrative',
      content: {
        cn: '1670 年 2 月 25 日——我生在 Saxony 的 Panitzsch——一个离 Leipzig 东 10 公里的小村。\n\n父亲 Matthias Winckelmann 是路德派牧师（Lutheran pastor）。\n\n你 21 世纪 7 年级听清楚: 路德派牧师跟天主教神父不一样——天主教神父不能结婚，路德派牧师可以娶妻生子。这是 1517 年 Martin Luther 宗教改革之后德国新教的特色——也是为什么我能生在一个有书的家庭。\n\nReformation Topic 你做过的那一段——Luther 1530s 推动 universal literacy（普及读书写字，因为新教徒要自己读 Bible 不靠神父）——结果之一: 17 世纪末 Saxony 农村女孩识字率比英国跟法国农村高。\n\n但你 careful framing 一下: 「能读 Bible」不等于「能学 Latin、数学、天文」。识字是普及的，高级学问还是男性专属。\n\n我之所以能学 Latin——因为父亲在家里教我。这是 anomaly（例外），不是 norm。\n\n1683 年我 13 岁。父亲死了，母亲不久后也死了。\n\n（17 世纪的中欧。三十年战争 1618-1648 之后人口少 30%，疾病传染，父母双亡的孩子很常见。）\n\n叔叔 Justinus Toellner 把我接走——他也是路德派牧师——他继续教我 Latin 跟神学。\n\n13 岁孤儿。能读 Latin。在 Saxony 农村。\n\n这是我故事的起点。',
        en: 'On 25 February 1670 — I was born in Panitzsch, a small village in Saxony, ten kilometers east of Leipzig.\n\nMy father, Matthias Winckelmann, was a Lutheran pastor.\n\n21st-century 7th grade hear this clearly: a Lutheran pastor is not a Catholic priest. A Catholic priest cannot marry; a Lutheran pastor can take a wife and raise children. This is one consequence of Martin Luther\'s 1517 Reformation — and it is one reason I was born into a household with books.\n\nIn the Reformation Topic you walked through, Luther in the 1530s pushed for universal literacy, because a Protestant was supposed to read the Bible directly, without a priest. One result: by the late 17th century, literacy among rural Saxon girls was higher than among rural English and French girls.\n\nCareful framing, though: "able to read the Bible" is not "able to study Latin, mathematics, astronomy." Basic literacy was widespread; advanced learning still belonged to men.\n\nI could learn Latin because my father taught me at home. That made me an anomaly, not a norm.\n\nIn 1683, when I was 13, my father died, and my mother followed soon after.\n\n(In late-17th-century central Europe, after the Thirty Years\' War of 1618-1648, the population had dropped by roughly 30 percent. Disease, then disease again. Orphaning was common.)\n\nMy uncle Justinus Toellner took me in. He too was a Lutheran pastor, and he kept teaching me Latin and theology.\n\nThirteen years old. An orphan. Able to read Latin. In the Saxon countryside.\n\nThis is where my story begins.',
      },
      deliverGoal: 'N1 1670 出生 Saxony Panitzsch 路德派牧师女儿 / Reformation 1530s universal literacy 17c 末 Saxony 农村女孩识字率高 / careful framing「读 Bible 不等于学 Latin/数学/天文」/ 1683 父母双亡 / 13 岁孤儿叔叔 Toellner 抚养教 Latin / 在 Saxony 农村 anomaly 不是 norm',
      engagementHook: '一个家庭背景给你「能进门」的机会——你 21 世纪有没有过这种「我能做这件事，是因为家里有人教过我」的感觉？',
      expectsRealAnswer: false,
    },
    {
      id: 'maria-n2',
      type: 'narrative',
      content: {
        cn: '1683 年——13 岁那年——叔叔把我送到 Sommerfeld 跟 Christoph Arnold 当学徒。\n\nChristoph Arnold（1650-1695）是 Saxony 一个奇怪的人。白天他是农民种地，晚上他是天文学家——self-taught peasant astronomer（自学农夫天文学家）。他自己磨望远镜镜片，自己跟 Leipzig 大学天文学家通信。1683 年他独立观测到那年的大彗星（后来 1705 年 Halley 才算出周期，所以那时还不叫哈雷彗星）。\n\nArnold 收我进家——不是当雇工，是 live-in apprentice（住家学徒）——这是 17 世纪欧洲学徒制 standard 模式，跟当时医学、木工、印刷学徒一样。\n\n我跟 Arnold 一家同住 9 年（1683-1692），学:\n\n1. Latin（天文学的 working language）\n2. 球面三角学（数学）\n3. 用 Arnold 的 4 ft 折射式望远镜观测\n4. 数据记录 + 写观测报告\n\n你 21 世纪 7 年级想象一下: 我一辈子没上过大学一天。欧洲所有大学都不收女性——一直要等到约 1900 年。我的全部天文知识来自 Arnold 学徒制——一种从中世纪 guild 系统遗留下来的旧机构。\n\n这里有一根 cross-Topic 钩子。Mali Topic 你做过的 Fatima al-Fihri：859 年她在摩洛哥 Fes 用父亲遗产创办 al-Qarawiyyin 大学（至今还在运营）。\n\n859 年伊斯兰世界的女性能创办大学——\n\n1683 年欧洲 Christian 世界的我连最低等的大学旁听资格都摸不到。\n\n这不是「伊斯兰对女性更好」——是「institution 形成期 vs 成熟期决定 historical visibility」。\n\n800 年差。',
        en: 'In 1683 — at 13 — my uncle sent me to Sommerfeld to apprentice with Christoph Arnold.\n\nChristoph Arnold (1650-1695) was a strange figure in Saxony. Farmer by day, astronomer by night — a self-taught peasant astronomer. He ground his own lenses and corresponded with astronomers at Leipzig University. In 1683 he independently observed that year\'s great comet (Halley would not calculate its period until 1705, so it was not yet "Halley\'s Comet").\n\nArnold took me into his household — not as a hired hand but as a live-in apprentice. This was the standard model in 17th-century Europe — the same model as medicine, carpentry, and printing apprenticeships of the day.\n\nI lived with Arnold\'s family for nine years (1683-1692), learning:\n\n1. Latin (the working language of astronomy)\n2. Spherical trigonometry\n3. Observation through Arnold\'s 4-foot refractor\n4. How to record data and write observation reports\n\n21st-century 7th grade picture this: I never spent a single day in a university. No European university admitted women — that wait would last until around 1900. All my astronomy came from an apprenticeship — an old institution carried forward from the medieval guild system.\n\nThere is a cross-Topic hook here. In the Mali Topic you met Fatima al-Fihri: in 859 she founded al-Qarawiyyin in Fes, Morocco, with her father\'s inheritance. The university still runs today.\n\nIn 859 a woman in the Islamic world could found a university.\n\nIn 1683, in Christian Europe, I could not even sit in on a university lecture.\n\nThis is not "Islam was kinder to women" — it is "the formation phase versus the mature phase of an institution decides who becomes historically visible."\n\nEight hundred years apart.',
      },
      deliverGoal: 'N2 1683-1692 13-22 岁 Christoph Arnold 学徒 9 年 (live-in apprentice — 中世纪 guild 系统遗留) / Saxony self-taught peasant astronomer 1683 独立观测大彗星 / 学 Latin + 球面三角学 + 4ft 折射式望远镜 + 写观测报告 / 一辈子没上过大学一天 (欧洲所有大学不收女性到 ~1900) / cross-Topic 钩子 Mali Fatima al-Fihri 859 创办 al-Qarawiyyin 大学 800 年差 / careful framing「institution 形成期 vs 成熟期决定 historical visibility」',
      engagementHook: '你 21 世纪 7 年级有没有「我学的东西不在学校里——是某个人手把手教的」这种经验？这种学法跟学校学法哪个更深？',
      expectsRealAnswer: false,
    },
    {
      id: 'maria-n3',
      type: 'narrative',
      content: {
        cn: '1692 年 5 月——我 22 岁——嫁给 Gottfried Kirch。\n\nGottfried 那年 50 岁，Berlin 一个有名的天文学家。第一任妻子 Maria Lange 1690 年死，留几个孩子。他要找新妻子——不只是为家，也为天文工作搭档。\n\n中间人是 Arnold——他认识 Gottfried（两人都在 Saxony astronomer 圈），写信介绍我。\n\n你 21 世纪 7 年级听 careful framing: 22 岁嫁 50 岁——你听到这里可能直接皱眉。我先不让你 judge，先给你三层 framing。\n\n第一层（最容易简化的）「下嫁老男人」——\n第二层（也容易简化的）「权力交易换天文 access」——\n第三层（21 世纪学界 Schiebinger 1989 ch. 4 pp. 82-90）「17c astronomy dual-pair 模式 standard entry point」。\n\n第三层什么意思?\n\n17 世纪欧洲天文学是 home-based craft——观测要在自家屋顶或私人观测台连续做。一个人撑不下来，所以「夫妻档」是 standard 工作单元: 丈夫上半夜，妻子下半夜，同台望远镜同份数据。\n\nMargaret Alic 1986《Hypatia\'s Heritage》 ch. 5 pp. 121-150 整理了数据: 17 世纪末德国 astronomer 96 人里 14 人是女性（14.6%）——几乎全是 wife / sister / daughter dual-pair 模式。\n\n你 Tang-Song Topic 见过的李清照（1084-约 1155，12 世纪的中国词人）也是「夫妻档」: 跟丈夫赵明诚一起编《金石录》，1129 年丈夫死后独立完成。但李清照名字进了文学史，因为她写词。\n\n我 1710 年丈夫死后独立工作——但我的名字没进 astronomy 史——因为「14% 这个数字反映的不是「德国对女性开放」，是「家庭作坊里看不见的劳动」」（Schiebinger 1989, p. 86）。\n\n22 岁那个春天我不知道这些。我只知道——我能进 Berlin。我能用最好的望远镜。',
        en: 'In May 1692, at 22, I married Gottfried Kirch.\n\nGottfried was 50, a well-known Berlin astronomer. His first wife, Maria Lange, had died in 1690, leaving several children. He needed a new wife — not only for the home but for an astronomy partner.\n\nArnold was the matchmaker. He knew Gottfried (both moved in Saxon astronomer circles) and wrote a letter of introduction for me.\n\n21st-century 7th grade, careful framing first: 22 marrying 50 — you may already be frowning. Hold the judgment one moment. Three layers.\n\nLayer one (easiest to oversimplify): "marrying down to an old man."\nLayer two (also easy): "power exchange for telescope access."\nLayer three (Schiebinger 1989, ch. 4, pp. 82-90): "the standard entry point of the 17th-century astronomy dual-pair."\n\nLayer three: what does that mean?\n\n17th-century European astronomy was home-based craft. Observation had to run continuously from a private rooftop or estate observatory. One person could not carry it. So the husband-wife dual was the standard working unit. Husband ran the early night, wife ran the late night, one telescope, one set of data.\n\nMargaret Alic\'s 1986 Hypatia\'s Heritage, ch. 5, pp. 121-150, gathered the numbers: of 96 documented German astronomers in the late 17th century, 14 were women — 14.6 percent — nearly all in wife, sister, or daughter dual-pair households.\n\nIn the Tang-Song Topic you met Li Qingzhao (1084-c. 1155), the 12th-century Chinese poet. She too was a "couple-team" — she and her husband Zhao Mingcheng compiled the Records on Metal and Stone together. After he died in 1129 she completed the work alone. Her name made it into Chinese literary history, because she wrote ci poetry.\n\nI worked alone after my husband died in 1710. My name did not make it into astronomy history. Because "the 14 percent figure does not reflect Germany\'s openness to women — it reflects the invisible labor inside the household workshop" (Schiebinger 1989, p. 86).\n\nThat spring at 22 I did not know any of this. I only knew: Berlin. The best telescope.',
      },
      deliverGoal: 'N3 1692.5 22 岁嫁 Gottfried Kirch 50 岁 / Arnold 介绍人 / careful framing 三层: 不是「下嫁」也不是「权力交易」是「17c astronomy dual-pair 模式 standard entry point」(Schiebinger 1989 ch. 4 pp. 82-90) / 17c 末德国 96 人 astronomer 14 人女性 (Alic 1986 ch. 5 pp. 121-150) / cross-Topic 钩 Tang-Song 李清照 12c 词人夫妻档 1129 丈夫死独立完成《金石录》——李清照名字进文学史 Maria 名字没进 astronomy 史 / 「14% 反映的不是德国对女性开放是家庭作坊看不见的劳动」',
      engagementHook: '一件事三层 framing——layer 1「下嫁」/ layer 2「权力交易」/ layer 3「dual-pair standard」——你 21 世纪能 hold 「同一件事三层不是相互否定」的复杂吗？',
      expectsRealAnswer: false,
    },
    {
      id: 'maria-n4',
      type: 'narrative',
      content: {
        cn: '1692 到 1700 年。我 22-30 岁。跟 Gottfried 在 Saxony 跟 Leipzig 工作 8 年。\n\n生 4 个孩子（3 个活到成年，全部进入天文）:\n- Christfried（1694-1740）儿子\n- Christine（1696-1782）女儿\n- Margaretha（1698-1759）女儿\n\nGottfried 跟我用同一台望远镜，同一份数据，同一个 Latin 写的报告。\n\n但 1700 年发生一件大事——\n\n1700 年 7 月 11 日——Brandenburg（勃兰登堡，普鲁士前身）选帝侯 Friedrich III 创办 Berlin Akademie der Wissenschaften（柏林科学院）。\n\n第一任 President 是 Leibniz（你 Lens 1 跟 Lens 2 都见过那个 Leibniz——Newton 微积分对手——也是 Mersenne 通信网的「孙辈」）。\n\nLeibniz 把模型从巴黎搬来: 1660 London Royal Society + 1666 Paris Académie + 1700 Berlin Academy——欧洲三大科学院的德国版。\n\nBerlin Academy 有一个主要 revenue source: 卖 calendar（历法）。每年帝国农民要买 calendar 看播种时节。所以 Academy 第一任 astronomer 的工作是「编 calendar + 观测」——institutional 重要。\n\nGottfried 1700 年 7 月任 Berlin Academy 第一任 astronomer + 月薪 500 thaler（银币——当时柏林一个工匠年薪约 100-150 thaler——所以 500/月 = 中产阶级）。\n\n我没有 official 职位。\n\n我搬进 Academy 观测台旁的公寓，跟 Gottfried + 4 个孩子住——\n\n我每天晚上用 Academy 的望远镜: 观测、记录、校对 Gottfried 的报告。\n\n但 Academy 的 payroll 上没有我名字。\n\nSchiebinger 1989 (p. 86) 一句很 sharp 的话: 「这跟现代「家庭主妇 GDP 不计入」是同一逻辑的 17c 版本。」\n\n你 21 世纪可能听过「无偿家务劳动」这个词。1700 年的 Berlin 已经在用同一种逻辑——只是给天文学家妻子用。',
        en: 'From 1692 to 1700 — I was 22 to 30 — Gottfried and I worked in Saxony and Leipzig for eight years.\n\nFour children (three lived to adulthood, all became astronomers):\n- Christfried (1694-1740), son\n- Christine (1696-1782), daughter\n- Margaretha (1698-1759), daughter\n\nGottfried and I used one telescope, one set of data, one Latin report.\n\nThen 1700 happened.\n\nOn 11 July 1700, Friedrich III, Elector of Brandenburg (predecessor of Prussia), founded the Berlin Akademie der Wissenschaften — the Berlin Academy of Sciences.\n\nIts first president was Leibniz (the same Leibniz from Lens 1 and Lens 2 — Newton\'s rival in the calculus dispute, and a "grandchild" of Mersenne\'s correspondence network).\n\nLeibniz copied the model from Paris: 1660 London Royal Society + 1666 Paris Académie + 1700 Berlin Academy — the German version of Europe\'s three great academies.\n\nBerlin Academy had one main revenue stream: selling calendars. Every year the empire\'s farmers needed a calendar to know planting dates. So the first astronomer\'s job was "edit the calendar and observe" — institutionally central.\n\nGottfried became the Academy\'s first astronomer in July 1700 with a monthly salary of 500 thaler (a Berlin craftsman earned roughly 100 to 150 thaler a year, so 500 a month was solid middle class).\n\nI had no official post.\n\nWe moved into the apartment beside the Academy observatory — Gottfried, the four children, and me.\n\nEvery night I used the Academy telescope — observed, recorded, edited Gottfried\'s reports.\n\nMy name was not on the Academy payroll.\n\nSchiebinger 1989, p. 86, a sharp sentence: "This is the 17th-century version of the same logic that today excludes housework from GDP."\n\nIn the 21st century you may have heard "unpaid household labor." Berlin in 1700 already ran the same logic — just on the wife of an astronomer.',
      },
      deliverGoal: 'N4 1692-1700 22-30 岁 Saxony+Leipzig 8 年 / 4 孩子 (3 活成 全部天文): Christfried 1694 / Christine 1696 / Margaretha 1698 / 1700.7.11 Brandenburg 选帝侯 Friedrich III 创办 Berlin Academy / Leibniz 第一任 President / 模仿 1660 Royal Society + 1666 Académie 德国版 / Gottfried 任第一任 astronomer 月薪 500 thaler 中产阶级 / Maria 没 official 职位 / Academy payroll 没她名字 / Schiebinger「现代家庭主妇 GDP 不计入是同一逻辑 17c 版本」',
      engagementHook: '「家庭主妇 GDP 不计入」——你 21 世纪听过这种说法吗？同一种逻辑 1700 年已经在 Berlin 跑——你怎么看「同样的工作付工资 vs 不付工资」?',
      expectsRealAnswer: false,
    },
    {
      id: 'maria-n5',
      type: 'narrative',
      content: {
        cn: '1702 年 4 月 21 日——我 32 岁——这一夜是我整辈子最重要的一夜。\n\n那夜——凌晨过零点不久——我一个人在 Berlin Academy 观测台值下半夜班。Gottfried 上半夜累了已睡。\n\n我用他的 4 ft 折射式望远镜，对准 Aquarius（宝瓶座）方向——那时主要观测项目是连续监测几颗已知星——\n\n我看到一颗模糊的星。比我前几夜记的位置——移动了。\n\n我记 RA（right ascension 赤经）+ Dec（declination 赤纬）。等了半小时——再观测——确认是 moving body。\n\n彗星。\n\n我下楼叫醒 Gottfried。他起床确认。1702 年 4 月 25 日——4 天后——他写信 Leibniz 通报。\n\n这就是 careful framing 出现的地方——\n\nGottfried 信原文（Latin）翻译: 「On the night of April 21st, my wife Maria, while observing the heavens, discovered a comet...」(4 月 21 日夜，我的妻子 Maria 在观测时发现一颗彗星。)\n\n信里清楚: 是 Maria 发现的。这一点没争议——史料铁证（Schiebinger 1989, pp. 82-90 引 Hannover Leibniz Archives 信件原文）。\n\n但 Berlin Academy 1702 年 5 月 official announcement——单挂 Gottfried 名。\n\n为什么? Schiebinger 1989 (p. 86) 给三层分析。\n\n第一层: Gottfried 没故意偷——他自己信里清楚说是我，跟 Leibniz 私人 acknowledge。\n\n第二层: 我自己同意了 dual-pair convention——17c astronomy 圈共识是「妻子工作算丈夫名下」。我没反对。\n\n第三层（最难 hold 的）: 真实压力来自 institution。如果用我单独署名——Berlin Academy 会拒绝把这颗彗星收入 official records，因为我不是 Academy 成员。Gottfried 单独署名 = 彗星进入 official 学术 record。我单独署名 = 彗星可能根本不被科学界认可。\n\n再加一层 careful framing: 1702 那颗彗星实际上不是真新彗星——是 1701-Comet C/1701 U1（Hevelius 团队 1701 年 10 月首次发现）的延续观测。我看到的是同一颗 1702 春天的回归。但我「独立观测 + 独立 identify 为彗星」（不是 nova 或其他现象）这个事实属实——这是 1702 年代欧洲 astronomy standard「discovery」定义。现代天文学定义更严，1702 那颗在现代 catalog 中归 Hevelius 1701，但这不影响我的工作认定。\n\n我那夜 32 岁。一颗彗星。一封信归丈夫名下。\n\n我等了 8 年——1710 年丈夫死后——才公开 claim。',
        en: 'On 21 April 1702 — I was 32 — the most important night of my life.\n\nShortly past midnight, I was alone at the Berlin Academy observatory on the late-night shift. Gottfried, who had run the early night, was already asleep.\n\nI pointed his 4-foot refractor at Aquarius — that period\'s main project was continuous monitoring of several known stars.\n\nI saw a faint star. It had moved from where I had logged it on previous nights.\n\nI recorded RA (right ascension) and Dec (declination). I waited half an hour, observed again, confirmed it was a moving body.\n\nA comet.\n\nI went downstairs and woke Gottfried. He confirmed. Four days later, on 25 April 1702, he wrote Leibniz.\n\nThis is where careful framing has to enter.\n\nGottfried\'s letter in translation (the original is Latin): "On the night of April 21st, my wife Maria, while observing the heavens, discovered a comet..."\n\nThe letter is plain: Maria discovered it. No dispute. The archival evidence is solid (Schiebinger 1989, pp. 82-90, citing the Hannover Leibniz Archives).\n\nBut the Berlin Academy\'s May 1702 official announcement carried only Gottfried\'s name.\n\nWhy? Schiebinger 1989, p. 86, gives three layers.\n\nLayer one: Gottfried did not "steal" it. His own letter says it was me; he acknowledges it to Leibniz in private.\n\nLayer two: I myself accepted the dual-pair convention. The 17th-century astronomy consensus was that "the wife\'s work counts under the husband\'s name." I did not push back.\n\nLayer three (hardest to hold): the real pressure was institutional. If the announcement listed only my name, the Berlin Academy would have refused to enter the comet into the official record, because I was not a member. Gottfried\'s name alone = the comet enters the official scientific record. My name alone = the comet might not be recognized as a discovery by the scientific community at all.\n\nOne more careful framing: the 1702 comet was not actually a new discovery — it was a continuation observation of comet C/1701 U1, first sighted by Hevelius\'s team in October 1701. What I saw was the same comet on its 1702 spring return. But "independent observation and independent identification as a comet" (not a nova or some other phenomenon) is true — and that was the standard definition of "discovery" in 1702 European astronomy. Modern astronomy defines discovery more strictly, and the 1702 comet now sits under Hevelius 1701 in the catalogs. None of which alters my work claim.\n\nThat night, at 32 — one comet — one letter — credit assigned to my husband.\n\nI waited eight years — until he died in 1710 — to claim it publicly.',
      },
      deliverGoal: 'N5 1702.4.21 凌晨 32 岁独立发现彗星 Aquarius 用 Gottfried 4ft 折射式望远镜 / Gottfried 1702.4.25 信 Leibniz 原文「my wife Maria... discovered」/ 但 Berlin Academy 1702.5 announcement 单挂 Gottfried 名 / Schiebinger 三层 framing: Gottfried 没故意偷 + Maria 同意 dual-pair convention + 真实压力 institutional (Maria 单署 Academy 拒入 official records) / careful framing: 1702 彗星实际是 Hevelius 1701 C/1701 U1 延续观测但 Maria「独立 identify 彗星」事实属实 / 1710 丈夫死后才公开 claim',
      engagementHook: '一颗彗星——三层 framing「丈夫没偷 + 我自己同意 + institution 强制」——你 21 世纪能 hold 「没人是坏人但结果坏」的复杂吗？',
      expectsRealAnswer: false,
    },
    {
      id: 'maria-n6',
      type: 'narrative',
      content: {
        cn: '1700 到 1710 年——我 30-40 岁——Berlin Academy 10 年。\n\n我跟 Gottfried 共同 catalogue（编星表）+ 编 calendar 卖给农民 + 教 4 个孩子天文。Christfried 6 岁开始磨颜料和望远镜镜片，Christine 4 岁开始记简单观测。我教孩子的方式跟 Arnold 当年教我一样——live-in apprenticeship。\n\n这 10 年里有一个时刻我想停下来跟你说——\n\n1687 年 7 月 5 日（你 Lens 1 见过的）Newton《Principia Mathematica》在 London 出版。我那年 17 岁，在 Saxony Sommerfeld 跟 Arnold 学 Latin，根本不知道 London 出了一本书。\n\n你 21 世纪 7 年级一定要看见这个时间不齐的切片:\n\n- 1687.7.5 那一天: Newton 44 岁，剑桥 Trinity College，《Principia》刚印好书页发出。\n- 同一天: Mersenne 已经死 39 年，但他 1620s-40s 的 78 人通信网（Descartes / Pascal / Galileo / Hobbes / Fermat / Roberval）已经 institutionalize 成 1660 Royal Society + 1666 Académie。\n- 同一天: 我 17 岁，在 Saxony 一个农夫家里抄 Arnold 的 Latin 笔记。\n\n三个人，三个地方，同一天，历史厚度不同。\n\n还有一根 cross-lens 钩子: 1644 年 Mersenne 给 Pascal 的信里讨论流体力学（fluid dynamics）——那封信通过 Pascal 1648《Treatise on the Equilibrium of Liquids》传到 Boyle 1662——传到 Newton 1687《Principia》Book 2 流体力学章。\n\n这条链 1644 到 1687 跑了 43 年。\n\n我 1700 年进 Berlin Academy 用的那台 4 ft 折射式望远镜——Gottfried 跟着 Mersenne 模型设计的工作流程（半夜分工 + Latin 报告 + 校对协议）——也是这条链的延续。\n\nMersenne 1648 死时 60 岁——他 1620 在巴黎修道院开始的网络——80 年后变成我用的工作方式。\n\n我没见过他。他没见过我。\n\n但我每晚用的工作 protocol——是他写的。',
        en: 'From 1700 to 1710 — I was 30 to 40 — ten years at the Berlin Academy.\n\nGottfried and I built joint catalogs, edited calendars to sell to farmers, taught the four children astronomy. Christfried began grinding pigment and lenses at 6; Christine began logging simple observations at 4. I taught the children the way Arnold had taught me — live-in apprenticeship.\n\nIn those ten years there is one moment I want to stop and show you.\n\n5 July 1687 — you met it in Lens 1 — Newton\'s Principia Mathematica was published in London. I was 17 that year, apprenticing with Arnold in Saxon Sommerfeld, copying Latin notes, with no idea a book had appeared in London.\n\n21st-century 7th grade, see this off-aligned time slice clearly:\n\n- 5 July 1687 — Newton, 44, Trinity College, Cambridge, fresh pages off the press.\n- Same day — Mersenne dead 39 years — but his 1620s-40s correspondence network of 78 (Descartes, Pascal, Galileo, Hobbes, Fermat, Roberval) had been institutionalized into the 1660 Royal Society and 1666 Académie.\n- Same day — me, 17, in a Saxon farmer\'s house, copying Arnold\'s Latin.\n\nThree people, three places, one day, three different historical thicknesses.\n\nA cross-lens hook: in 1644 Mersenne wrote Pascal a letter about fluid dynamics. That letter ran through Pascal\'s 1648 Treatise on the Equilibrium of Liquids, then through Boyle 1662, then into Newton\'s 1687 Principia Book 2.\n\nThe chain ran 43 years from 1644 to 1687.\n\nThe 4-foot refractor I used at the Berlin Academy from 1700 onward — and Gottfried\'s working procedures (split nights, Latin reports, peer-checking protocol) — were also a continuation of that chain.\n\nMersenne died at 60 in 1648. The network he started in a Paris monastery in 1620 became, 80 years later, the way I worked every night.\n\nI never met him. He never met me.\n\nBut the protocol I used each night — he wrote it.',
      },
      deliverGoal: 'N6 1700-1710 30-40 岁 Berlin 10 年 / 共同 catalogue + 编 calendar + 教 4 孩子天文 / 1687.7.5《Principia》出版三 lens 时间不齐切片 ⭐ cross-lens micro-detail: Newton 44 岁 + Mersenne 死 39 年 + Maria 17 岁 Saxony 学 Latin / 1644 Mersenne→Pascal 1648→Boyle 1662→Newton 1687 Principia Book 2 流体力学链 ⭐ 跨 lens (Lens 2 Mersenne 网络遗产) / Maria 1700 用的工作 protocol 是 Mersenne 写的 / 「我没见过他他没见过我但我每晚用的工作 protocol 是他写的」',
      engagementHook: '同一天——三个人在三个地方——历史厚度不同——你 21 世纪能想象「我跟某个人没见过面，但他写的东西决定我每天怎么工作」吗？',
      expectsRealAnswer: false,
    },
    {
      id: 'maria-n7',
      type: 'narrative',
      content: {
        cn: '1710 年 7 月 25 日——Gottfried 死了——71 岁。\n\n我 40 岁守寡。\n\n3 个月后——1710 年 10 月——我正式申请接任 Berlin Academy astronomer 职位。\n\n我的 case 强:\n- 18 年观测经验（1692-1710）\n- 1702 彗星发现（Leibniz 已私下确认是我）\n- 已在 Berlin Academy 观测台日常工作 8 年（1702-1710 半数观测我做）\n- 知道所有 instruments / 数据 / calendar 编制流程\n\nLeibniz 作为 Academy President 强力支持。Leibniz 1710 年 10 月 18 日给 Berlin Academy Council 的信原文（Schiebinger 1989, p. 95）:\n\n「Frau Kirch is one of the most learned astronomers now living. She has performed services to the Academy that no man in our employ could have done better. To dismiss her now would be a great injustice and a great loss.」\n\n（Frau Kirch 女士是当今活着的最博学的天文学家之一。她为 Academy 做的工作，我们雇的任何男人都做不到更好。现在赶她走是巨大的不公也是巨大的损失。）\n\nLeibniz 是 Newton 的微积分对手，是 Mersenne 网络的「孙辈」，1700 年自己创办的 Academy。他自己赌上声誉支持我。\n\n但 1711 年 1 月 18 日 Berlin Academy Council 否决了 Leibniz 自己。\n\nCouncil Minutes 德文原文（现存 Berlin-Brandenburg Academy archives，Schiebinger 1989, p. 96 引）:\n\n「Es würde unserer Akademie wenig Ehre bringen, wenn ein Frauenzimmer als Astronom angestellt würde.」\n\n（如果一个 Frauenzimmer 被雇为 astronomer，会给我们 Academy 带来很少的荣誉。）\n\ninline gloss: Frauenzimmer 是 17-18c 德语，字面意思「女性的房间」（women\'s apartments）。用「房间」代指「女性」是当时德语 standard idiom，暗含「女性应留私人空间，不应公开露面」的 patriarchal 假设。Council 用这个词不是 neutral，是带 semantic loading 的。\n\n你 21 世纪 7 年级听清楚: 我不是因为「不够 qualified」被拒，Leibniz 已认证。真实理由是: 一旦我任职，Academy 就开了「女性可任职」先例，未来无法关门。Council 怕这个 institutional precedent。\n\n这里有一根 cross-lens 钩子。同一年 1710——Cambridge 用「Arian 异端」开除 William Whiston（Newton 的 protégé，接 Newton Lucasian Chair 的人）。两个 institution 用不同理由开除两种不可见信仰（女性身份 / 异端神学）——但同一种 logic「我们怕开先例」。\n\nIliffe 2017《Priest of Nature》(Oxford) 把这两件事放进同一个 institutional 自我保护框架。1710-1712 是新生科学机构最 sharp 的「关门」时刻。',
        en: 'On 25 July 1710 Gottfried died, at 71.\n\nI was 40, a widow.\n\nThree months later, in October 1710, I formally applied to succeed him as Berlin Academy astronomer.\n\nMy case was strong:\n- 18 years of observation (1692-1710)\n- the 1702 comet (Leibniz had already privately confirmed it was mine)\n- 8 years already inside the Berlin Academy observatory, doing roughly half the observations from 1702 to 1710\n- mastery of every instrument, dataset, and step of the calendar pipeline\n\nLeibniz, as Academy president, threw his weight behind me. His 18 October 1710 letter to the Berlin Academy Council (Schiebinger 1989, p. 95):\n\n"Frau Kirch is one of the most learned astronomers now living. She has performed services to the Academy that no man in our employ could have done better. To dismiss her now would be a great injustice and a great loss."\n\nLeibniz — Newton\'s rival in the calculus dispute, "grandchild" of Mersenne\'s network, founder of the Academy in 1700 — staked his own reputation on me.\n\nOn 18 January 1711 the Berlin Academy Council overruled Leibniz himself.\n\nThe minutes, in German (Berlin-Brandenburg Academy archives, Schiebinger 1989, p. 96):\n\n"Es würde unserer Akademie wenig Ehre bringen, wenn ein Frauenzimmer als Astronom angestellt würde."\n\n("If a Frauenzimmer were employed as astronomer, it would bring little honor to our Academy.")\n\nInline gloss: Frauenzimmer — 17th-18th-century German — literally "women\'s apartments." Using "the rooms" to stand for "women" was standard idiom of the day, carrying the patriarchal assumption that women belonged in private spaces and should not appear in public. The Council\'s choice of word was not neutral — it was semantically loaded.\n\n21st-century 7th grade hear this clearly: I was not refused for lack of qualifications. Leibniz had certified me. The real reason was that the moment I was appointed, the Academy would have set a "women may hold posts" precedent — a door it could not later close. The Council feared the institutional precedent.\n\nA cross-lens hook: in the same year, 1710, Cambridge expelled William Whiston (Newton\'s protégé, his successor in the Lucasian Chair) on charges of Arian heresy. Two institutions, two different official reasons, two different invisible affiliations (gender, theological heresy) — but the same logic: "we fear the precedent."\n\nIliffe 2017, Priest of Nature (Oxford), places both events inside one frame of institutional self-protection. 1710-1712 is the sharpest "closing the door" moment in the new scientific institutions.',
      },
      deliverGoal: 'N7 1710.7.25 Gottfried 死 71 岁 / Maria 40 岁守寡 / 1710.10 申请接任 Berlin Academy astronomer / 18 年经验 + 1702 彗星 + 8 年日常工作 + 知道所有流程 / Leibniz 1710.10.18 信原文「one of the most learned astronomers now living」/ 1711.1.18 Council 否决德文 minutes 原文「Es würde unserer Akademie wenig Ehre bringen, wenn ein Frauenzimmer als Astronom angestellt würde」 ⭐ archive 级 / Frauenzimmer inline gloss 17-18c 德语 patriarchal semantic loading / 真实理由「institutional precedent fear」/ ⭐ cross-lens 钩 1710 Cambridge 开除 Whiston (Newton protégé) Arian 异端 同 institutional 自我保护 (Iliffe 2017)',
      engagementHook: '「我们怕开先例」——你 21 世纪有没有过这种「他们不是反对你这个人——是怕你后面带来的人」的感觉？',
      expectsRealAnswer: false,
    },
    {
      id: 'maria-n8',
      type: 'narrative',
      content: {
        cn: '1711 年 1 月——Council 否决之后——Academy 给我的「补偿」:\n\n- 100 thaler 一次性抚恤（相当于 Gottfried 月薪的 1/5——他活着每月领 500，他死后给我一次 100）\n- 让我跟 4 个孩子 3 个月内搬出 Academy 观测台公寓\n- 不再有任何 official 关系\n\n4 个月后——1711 年 4 月——我写信 Berlin Academy。这封信现存 Berlin-Brandenburg Academy archives，Schiebinger 1989, p. 97 引原文:\n\n「When my husband was alive, no one objected to my work. Now they object only because I am a widow. The work I did then is the same work I would do now. What has changed is not my hand but my position.」\n\n（我丈夫活着的时候，没人反对我的工作。现在他们反对，只因为我守寡了。我那时做的工作，现在也能做。变的不是我的手，是我的身份。）\n\n这封信是这一段最关键的史料。\n\n你 21 世纪 7 年级 careful 读: 这不是 victim narrative。我没说「他们坏」也没说「我可怜」。我做的是 institutional analysis（机构分析）——我精准指出「身份 vs 工作」的脱钩:\n\n- 身份: married → widow（在变）\n- 工作: 同一台望远镜同一种观测同一份报告（没变）\n- access: 只有身份决定（institutional rule）\n\n这是 receiving-end 最高的清醒度——不是哭，是精准。\n\n这里有一根 cross-lens 钩子。你 Byzantine Topic 见过的 Theodora 皇后（6c）N6 那一段——525 年她从妓女出身嫁 Justinian。东罗马法律 426 年禁演员阶级娶贵族，Justinian 535 改法。Theodora 立后那一刻她说过类似的话: 「变的是法律，不是我」。\n\n两种文明，两个时代——12 个世纪的差距——同一种 receiving-end 清醒。\n\n「我夫」cultural ban——「丈夫活着我的工作算他名下，丈夫死了我连工作都没了」——这是跨文明的 pattern。\n\nMaria 不是第一个——也不是最后一个。\n\n但 Maria 1711 年 4 月那封信把这个 pattern 写下来，存进 archive。300 年后被你读到。\n\n这就是「写下来」的力量。',
        en: 'In January 1711, after the Council\'s refusal, the Academy offered me "compensation":\n\n- 100 thaler one-time bereavement payment (one fifth of Gottfried\'s monthly salary — he had earned 500 a month alive; the day he died they gave me 100)\n- three months to move myself and four children out of the observatory apartment\n- no further official relationship\n\nFour months later, in April 1711, I wrote the Berlin Academy. The letter survives in the Berlin-Brandenburg Academy archives; Schiebinger 1989, p. 97, quotes it:\n\n"When my husband was alive, no one objected to my work. Now they object only because I am a widow. The work I did then is the same work I would do now. What has changed is not my hand but my position."\n\nThis letter is the sharpest single source on this stretch.\n\n21st-century 7th grade, read it carefully: it is not a victim narrative. I do not say "they are evil" and I do not say "I am pitiful." What I do is institutional analysis. I name precisely the decoupling of position and work:\n\n- position: married then widow (changing)\n- work: the same telescope, the same observation, the same report (not changing)\n- access: decided only by position (institutional rule)\n\nThis is the highest clarity available on the receiving end — not weeping, but precision.\n\nA cross-lens hook: in the Byzantine Topic you met the 6th-century Empress Theodora, N6. In 525 she married Justinian out of an actress\'s background. East Roman law since 426 had forbidden actresses to marry the patrician class. In 535 Justinian rewrote the law. The moment she was crowned empress, Theodora is said to have spoken similarly: "What changed is the law, not me."\n\nTwo civilizations, two eras, twelve centuries apart — the same receiving-end clarity.\n\nThe pattern of "the husband\'s shadow" — "while my husband lives my work counts under his name; once he dies even the work disappears" — is cross-civilizational.\n\nMaria was not the first. Maria will not be the last.\n\nBut what Maria did in April 1711 was write it down. The letter went into the archive. Three hundred years later you are reading it.\n\nThat is the power of "putting it on paper."',
      },
      deliverGoal: 'N8 1711.1 Academy 补偿 100 thaler (Gottfried 月薪 1/5) + 3 个月搬出公寓 + 不再 official 关系 / 1711.4 Maria 抗议信原文「When my husband was alive, no one objected to my work. Now they object only because I am a widow. The work I did then is the same work I would do now. What has changed is not my hand but my position.」⭐ archive 级 / 不是 victim narrative 是 sharp institutional analysis (身份 vs 工作脱钩) / receiving-end 最高清醒度 / ⭐ cross-lens 钩 Byzantine Theodora N6 525 嫁 Justinian 同 pattern「变的是法律不是我」12 世纪差跨文明 receiving-end 清醒 / 「写下来 archive 300 年后你读到」',
      engagementHook: '「变的不是我的手，是我的身份」——这一句你 21 世纪能用在自己身上的什么时刻吗？',
      expectsRealAnswer: false,
    },
    {
      id: 'maria-n9',
      type: 'narrative',
      content: {
        cn: '1711 年 5 月——我跟 4 个孩子搬出 Berlin Academy 观测台公寓——\n\n1712 年 5 月。我 42 岁，进入 Berlin 商人 Bernhard Friedrich von Krosigk（1656-1714）家做私人 astronomer。Krosigk 是 Berlin 富商，业余天文爱好，自家盖了私人观测台。\n\n我在 Krosigk 家 2 年——工作内容跟 Berlin Academy 时期一样: 观测 + 编 calendar + 培训学徒——\n\n但没有 institutional title。\n\n1714 年 4 月——Krosigk 死了——我又失业。\n\n1714 年夏天——44 岁——我做了一个决定: 移居 Danzig（现波兰 Gdańsk）。\n\n这里有一个 cross-lens 时刻你 careful 听清楚——\n\nDanzig 那时是 Polish-Lithuanian Commonwealth（波立联邦）治下的 Hanseatic League 港口。1641 年 Johannes Hevelius（1611-1687）用家族酿酒生意的钱在自家屋顶盖了 Stellaeburgum（星之城堡，17 世纪欧洲最大私人天文观测台之一）。Hevelius 1663 年 52 岁娶 16 岁的 Elisabetha Koopmann（1647-1693），两人年龄差 36 岁，18 年夫妻档天文（1663-1681）+ 1681-1687 后期 Elisabetha 主导。\n\n1687 年 1 月 28 日 Hevelius 死（76 岁生日当天），Elisabetha 40 岁守寡，接下来 6 年（1687-1693）独立完成丈夫遗著《Prodromus Astronomiae》（1690 出版）。书收录 1564 颗星位置，比 Tycho 1602 catalog 多 50%，是 17c 末欧洲 standard reference。\n\n1693 年 12 月 22 日 Elisabetha 死 46 岁——Hevelius 后人（女儿 Catharina Elisabetha）继续维护观测台到 18c 初。\n\n你 Lens 2 §11.5 见过这一段——\n\n1714 年我 44 岁移居 Danzig——不是去陌生地方——是去「另一个 dual-pair 寡妇 Elisabetha 留下的废墟」。\n\n同一栋观测台:\n- 1641 Hevelius 建（30 岁）\n- 1663 娶 Elisabetha（52 岁 + 16 岁）\n- 1687 Hevelius 死（Elisabetha 接手 6 年）\n- 1693 Elisabetha 死（女儿维护）\n- 1714 我 44 岁来工作（编 calendar 维持生计）\n\n一栋楼跨两代女性 astronomer: Elisabetha 1663-1693（30 年）→ Maria Kirch 1714-1716（2 年）。中间隔 21 年但用同一栋楼，同一种「妻子+丈夫合作 dual-pair」的工作模式。\n\n我在 Danzig 1714-1716 编 calendar 卖给 Saxony / Pomerania 农民——卖出去的 calendar 没我名字——挂的是「Berlin 系传承编者」。\n\n两年。同一栋观测台。两个寡妇。同一根传承链。\n\n这条链——你 21 世纪 7 年级——是 17c 德语区天文夫妻档的物理基础设施。',
        en: 'May 1711 — my four children and I left the Berlin Academy observatory apartment.\n\nMay 1712, at 42, I entered the household of the Berlin merchant Bernhard Friedrich von Krosigk (1656-1714) as private astronomer. Krosigk was a wealthy merchant, a serious amateur observer, with a private observatory on his estate.\n\nFor two years at Krosigk\'s I did the same work as at the Berlin Academy: observe, edit the calendar, train apprentices.\n\nNo institutional title.\n\nApril 1714 — Krosigk died — I lost the post again.\n\nSummer 1714, at 44, I made a decision: move to Danzig (today Gdańsk, Poland).\n\nA careful cross-lens moment here.\n\nDanzig was then a Hanseatic port under the Polish-Lithuanian Commonwealth. In 1641 Johannes Hevelius (1611-1687) had used his family\'s brewing income to build Stellaeburgum on his own roof — Star-Castle, one of the largest private observatories in 17th-century Europe. In 1663, at 52, Hevelius married 16-year-old Elisabetha Koopmann (1647-1693). A 36-year age gap. Eighteen years of dual-pair astronomy (1663-1681), then 1681-1687 with Elisabetha increasingly in the lead.\n\nOn 28 January 1687 Hevelius died on his 76th birthday. Elisabetha was 40, a widow. Over the next six years (1687-1693) she alone completed his unpublished Prodromus Astronomiae (printed 1690) — 1564 stars catalogued, fifty percent more than Tycho\'s 1602 catalog — the standard European reference until Flamsteed.\n\nOn 22 December 1693 Elisabetha died at 46. Hevelius\'s descendants (their daughter Catharina Elisabetha) kept the observatory running into the early 18th century.\n\nYou met this in Lens 2, §11.5.\n\nIn 1714, at 44, I moved to Danzig — not to a strange place, but into "the ruins another dual-pair widow had left."\n\nOne building:\n- 1641 Hevelius built it (30)\n- 1663 he married Elisabetha (52 and 16)\n- 1687 Hevelius died (Elisabetha carried on six years)\n- 1693 Elisabetha died (the daughter maintained it)\n- 1714 I arrived at 44 to work (editing calendars to make rent)\n\nOne building across two generations of women astronomers — Elisabetha 1663-1693 (30 years), then Maria Kirch 1714-1716 (2 years) — separated by 21 years but inside the same walls, inside the same wife-and-husband dual-pair working pattern.\n\nFor two years in Danzig, 1714-1716, I edited calendars for Saxon and Pomeranian farmers. None of those calendars carried my name. They were issued under "Berlin-school continuator."\n\nTwo years. One observatory. Two widows. One chain of inheritance.\n\nThis chain — 21st-century 7th grade — is the physical infrastructure of the 17th-century German-speaking astronomy dual-pair tradition.',
      },
      deliverGoal: 'N9 1711.5 搬出公寓 / 1712-1714 Bernhard Friedrich von Krosigk Berlin 商人家私人 astronomer 2 年 (1714.4 Krosigk 死又失业) / 1714 夏 44 岁移居 Danzig / ⭐ cross-lens micro-detail Hevelius 老观测台 1641 Stellaeburgum (Lens 2 §11.5 bridge): 1641 Hevelius 30 岁建 / 1663 娶 16 岁 Elisabetha Koopmann (52+16 岁差 36 年 18 年夫妻档) / 1687 Hevelius 死 (Elisabetha 接 6 年完成《Prodromus Astronomiae》1690 出版 1564 颗星比 Tycho 1602 catalog 多 50% standard reference) / 1693 Elisabetha 死 / 1714 Maria 44 岁来工作编 calendar 维持生计 / 「另一个 dual-pair 寡妇 Elisabetha 留下的废墟」/ 一栋楼跨两代女性 astronomer 21 年隔 / 17c 德语区天文夫妻档物理基础设施',
      engagementHook: '一栋楼跨两代——你 21 世纪所在的城市，有没有这种「同一栋建筑里换了几代人做同一种事」的地方？',
      expectsRealAnswer: false,
    },
    {
      id: 'maria-n10',
      type: 'narrative',
      content: {
        cn: '1716 年。我 46 岁，在 Danzig 编了 2 年 calendar，攒了一点钱。\n\n1713 年 2 月普鲁士国王 Friedrich I 死，子 Friedrich Wilhelm I（士兵王）继位。1716 重组 Berlin Academy 财政，重启 astronomer 职位。\n\n但 Berlin Academy 没给我——给了我 23 岁的儿子 Christfried Kirch（生于 1694——在 Leipzig 读 Latin school + 在我家学天文）。\n\n1717 年春 Christfried 23 岁正式接任 Berlin Academy astronomer 职位——\n\n我 47 岁回 Berlin——\n\n不是作为 astronomer——是作为 Christfried 的「assistant」（助手）。\n\n你 21 世纪 7 年级 careful 听: 我做了 Christfried 这辈子做不到的工作——但 institutional title 是 Christfried 的。\n\nSchiebinger 1989 (pp. 102-103) 最 cutting 的一段:\n\n「Maria Kirch returned in 1717 to the same observatory where she had worked from 1700 to 1711, using the same telescope, doing the same work — but now as her son\'s assistant, not as the founder. She had become invisible inside her own life\'s work.」\n\n（Maria 1717 回到她 1700-1711 工作过的同一个观测台，用同一台望远镜，做同样的工作——但现在是她儿子的助手，不是创建者。她在自己一生的工作里变得不可见。）\n\n47 岁到 50 岁。我在 Berlin 同一栋观测台又工作了 3 年。\n\n1720 年 12 月 29 日——我死。50 岁。Berlin 家中。死因 fever（热病——17c 通常指 typhus 或类似感染）。\n\n葬于 Berlin Sophienkirche（索菲亚教堂），现 Berlin Mitte 区 Große Hamburger Straße。教堂还在，墓碑已不存（1945 战火 + 战后改建）。\n\nChristfried 1721 年给我写讣告（eulogy）在《Acta Eruditorum》（德国学术杂志——也是 Leibniz 1684 发表微积分的杂志）:\n\n「She continued the work of her husband and instructed her children in the same. The Academy owes much to her, though it has acknowledged little.」\n\n（她延续丈夫的工作，也教导孩子。Academy 欠她很多，虽然它没承认多少。）\n\nChristfried 自己 1740 年死（46 岁）——没结婚——没继承人。\n\n两个女儿 Christine + Margaretha 继续做 astronomer 在 Berlin Academy 直到 1759 / 1782 死——都是「assistant」——都没 official title。\n\n同一栋观测台 1700-1782，82 年，一个家庭三代女性，零 official title。\n\n你 21 世纪 7 年级停一下: 同一栋观测台。同一台望远镜。同一种工作。\n\n谁是 founder。谁是 helper。\n\n性别决定。',
        en: '1716 — at 46 — after two years editing calendars in Danzig, I had saved a little.\n\nIn February 1713 the Prussian King Friedrich I died, and his son Friedrich Wilhelm I — the Soldier King — succeeded. In 1716 he restructured Berlin Academy finances and reopened the astronomer post.\n\nBerlin Academy did not give it to me. They gave it to my 23-year-old son Christfried Kirch (born 1694, Latin school in Leipzig, his astronomy from me).\n\nIn spring 1717 Christfried, at 23, formally took the Berlin Academy astronomer post.\n\nI returned to Berlin at 47.\n\nNot as astronomer. As Christfried\'s "assistant."\n\n21st-century 7th grade, listen carefully: I was doing work my son could not have done — but the institutional title was his.\n\nSchiebinger 1989, pp. 102-103, the cutting passage:\n\n"Maria Kirch returned in 1717 to the same observatory where she had worked from 1700 to 1711, using the same telescope, doing the same work — but now as her son\'s assistant, not as the founder. She had become invisible inside her own life\'s work."\n\nFrom 47 to 50 — three more years inside the same Berlin building.\n\nOn 29 December 1720 — I died. 50 years old. At home in Berlin. Cause: fever (in the 17th century usually typhus or a similar infection).\n\nBuried at Berlin Sophienkirche, today Große Hamburger Straße, Berlin Mitte. The church still stands. The headstone is gone (1945 war damage and postwar reconstruction).\n\nIn 1721 Christfried wrote my eulogy in Acta Eruditorum (the German learned journal where Leibniz had published calculus in 1684):\n\n"She continued the work of her husband and instructed her children in the same. The Academy owes much to her, though it has acknowledged little."\n\nChristfried himself died in 1740 at 46, never married, no heirs.\n\nMy two daughters Christine and Margaretha kept working as astronomers at the Berlin Academy until they died in 1759 and 1782 — both as "assistants," neither with an official title.\n\nOne observatory, 1700 to 1782. Eighty-two years. One family, three generations of women. Zero official titles.\n\n21st-century 7th grade pause here: one observatory, one telescope, one kind of work.\n\nWho is founder. Who is helper.\n\nGender decides.',
      },
      deliverGoal: 'N10 1716 普鲁士新王 Friedrich Wilhelm I 重启 astronomer / Berlin Academy 给 23 岁儿子 Christfried 不给 Maria / 1717 47 岁回 Berlin 做 son\'s assistant 同一栋观测台 / Schiebinger pp. 102-103 cutting passage「She had become invisible inside her own life\'s work」⭐ archive 级 / 1720.12.29 死 50 岁 fever / 葬 Sophienkirche 现 Mitte 区 Große Hamburger Straße 墓碑 1945 战火 + 战后改建无 / Christfried 1721《Acta Eruditorum》讣告原文「The Academy owes much to her, though it has acknowledged little」/ 两女 Christine 1759 + Margaretha 1782 继续 assistant 都无 official title / 一栋楼 1700-1782 82 年三代女性零 official title / 「同一栋观测台 founder→helper 性别决定」',
      engagementHook: '「她在自己一生的工作里变得不可见」——你 21 世纪听到这句最难受的是哪一部分？',
      expectsRealAnswer: false,
    },
    {
      id: 'maria-n11',
      type: 'synthesis',
      content: {
        cn: '我已死 305 年——你 21 世纪 7 年级跟我做完这一段——\n\n你坐 30 秒——想一个问题——\n\n你身边——「同一栋楼 founder vs helper 性别决定」是谁?\n\n21 世纪 5 个常见样本:\n\n第一: STEM 实验室女博士。她做了 6 年实验，论文发出来，通讯作者是男导师（PI），她是第二作者。3 年后她离开学术圈回家带孩子。\n\n第二: 创业 cofounder 老婆。她跟丈夫 2014 年一起开公司，她写产品代码，他出去融资。2020 年公司上市，他名字进招股书 founder 一栏，她是 employee 13 号。婚姻里两个人但 history 一个人。\n\n第三: 公司贡献 invisible 女员工。她在 office 8 年，做了所有给客户写报告的脏活。升职给了 1 年的男同事，理由「他更有 leadership 气场」。\n\n第四: 跨国家庭 work-from-home 妻子。她在家带 2 个孩子，同时做 freelance 翻译。丈夫 LinkedIn 上写「dual-career couple」，她 LinkedIn 上写「mother」。\n\n第五: 学术圈第二作者。她写了论文 80%，导师挂第一作者。她毕业了找工作，简历上没法解释「为什么我做了 80% 但是第二作者」。\n\n5 个样本，300 年差，同一种 receiving-end pattern。\n\n你身边的呢?\n\n你妈妈、你姐姐、你某个 aunt——\n\n或者——\n\n你自己?\n\n你现在 12 岁。可能还没遇到这件事，也可能已经遇到了「我做了 group project 80% 但 grade 跟 group leader 一样」的小版本。\n\n你不用现在 solve——\n\n你只要——把这条 pattern 看见——\n\n看见就是第一步。\n\nMaria 1711 年 4 月写那封信——300 年后被你读到——是因为她「写下来」。\n\n你看见——也是「写下来」的一种。\n\n你 21 世纪——你身边「同一栋楼 founder vs helper 性别决定」是谁?\n\n如果是你自己——\n\n你想怎么写下来?',
        en: 'I have been dead 305 years. You, 21st-century 7th grade, have walked this lens with me.\n\nSit thirty seconds with one question.\n\nNear you — who is the "same building, founder versus helper, decided by gender" person?\n\nFive familiar 21st-century cases:\n\nOne: the woman PhD in a STEM lab. Six years of experiments. The paper publishes. The corresponding author is her male PI. She is second author. Three years later she leaves academia for childcare.\n\nTwo: the cofounder-wife of a startup. She and her husband opened the company in 2014. She wrote the product code; he raised the money. 2020 — IPO. His name on the prospectus founder line. She is employee number 13. Two people in the marriage; one person in the history.\n\nThree: the invisible woman at the office. Eight years inside, she did the dirty client-report work the whole time. The promotion went to a man who had been there one year. The reason: "he has more leadership presence."\n\nFour: the work-from-home wife in a transnational household. Two children at home, freelance translation alongside. Her husband\'s LinkedIn says "dual-career couple." Hers says "mother."\n\nFive: the second-author scholar. She wrote 80 percent of the paper. Her advisor took first authorship. She graduates, looks for a job, and has no way to explain "I did 80 percent of this but I am second author" on her CV.\n\nFive cases. Three hundred years apart. The same receiving-end pattern.\n\nWho is yours?\n\nYour mother, your sister, an aunt —\n\nor —\n\nyou?\n\nYou are 12 now. Maybe you have not met this yet. Maybe you have, in the small version: "I did 80 percent of the group project and got the same grade as the group leader."\n\nYou do not have to solve it now.\n\nYou only have to — see the pattern.\n\nSeeing is the first step.\n\nMy April 1711 letter survived 300 years to reach you because I wrote it down.\n\nYour seeing it is a kind of writing it down.\n\n21st-century — near you, who is the "same building, founder versus helper, gender decides" person?\n\nIf the answer is you —\n\nhow do you intend to write it down?',
      },
      deliverGoal: 'N11 receiving-end reflection 21c 5 个「同一栋楼 founder vs helper 性别决定」样本: STEM 女博士第二作者 / 创业 cofounder 老婆 / 公司 invisible 女员工 / 跨国家庭 work-from-home 妻子 / 学术圈 80% 第二作者 / 「你身边谁? 你自己?」/ Maria 1711 信「写下来」300 年后被读到 / 看见就是第一步 / 「你想怎么写下来?」expectsRealAnswer:true',
      engagementHook: '你身边「同一栋楼 founder vs helper 性别决定」是谁? 你妈妈/姐姐/aunt——或者你自己?',
      expectsRealAnswer: true,
    },
    {
      id: 'maria-n12',
      type: 'synthesis',
      content: {
        cn: '我已死 305 年。你跟我做完 receiving-end Lens 3 这一段，你已经做完 Phase 1 全部 Topics 的 receiving-end lens。\n\n横向看 8 个 receiving-end 没名字 / 有名字的女性 voice——跨 6 文明 1100 年:\n\n4 真:\n- Sorghaghtani Beki（Mongol Empire 真实，1190-1252）: Töregene 时代蒙古真实政治家\n- Theodora Empress（Byzantine Rise 真实，c.500-548）: 6c 拜占庭皇后\n- Li Qingzhao 李清照（Tang-Song 真实，1084-c.1155）: 12c 中国词人\n- 我 Maria Kirch（Scientific Revolution 真实，1670-1720）: 17-18c 德国天文学家\n\n4 虚（fictional composite）:\n- Anna the Iconographer（Byzantine 虚 fictionalDisclaimer 模式，c.710-820）: 8c 圣像派修女\n- Anacaona Jr（Age of Exploration 虚，1492-1504）: 12 岁 Taíno 女孩\n- Aisha 1413（Mali 虚）: 14 岁 Mande 女孩\n- Sister Agnes（Reformation 虚）: 16c 修女\n\n8 个人，4 真 + 4 虚，跨 6 个文明（Mongol / Byzantine / 中国 / 加勒比 / Mali / 德国），跨 1100 年（约 8c 到 18c 初）。\n\n同一根 receiving-end pattern——\n\n「机构活了。个人故事消失。」\n\nBerlin Academy 还在，今天叫 Berlin-Brandenburgische Akademie der Wissenschaften，成立 325 年。\n\nLi Qingzhao 编的《金石录》还在——\n\nHagia Sophia 还在——\n\n但 Maria 1702 那颗彗星不在我名下——\n\nLi Qingzhao 1129 之后那 26 年的孤独工作不在中国官方文学史正文——\n\nAnna 跟 Theodosia 不在 843 Triumph of Orthodoxy 名单——\n\nAisha 妈妈不在 Mali 王朝史——\n\nAnacaona Jr 不在 Columbus 日记——\n\n你 21 世纪 7 年级——你已经看见了 8 个 voice。你现在知道这条 pattern。你 12-13 岁要看见这条链——这是 Phase 1 我们送你的礼物。\n\n你接下来怎么活——\n\n是另一个问题。\n\n但你已经看见了。\n\n你看见——就不一样了。\n\n你想 30 秒——\n\n8 个人里——哪个让你最难忘?\n\n哪个故事——你想自己——也写下来一段?\n\n你写——就是第 9 个。\n\n你写——300 年后被读到——就是 Maria 1711 那封信的延续。\n\n你想写谁?',
        en: 'I have been dead 305 years. You and I have walked Lens 3, the receiving-end lens, together. You have now walked the receiving-end lens for every Topic in Phase 1.\n\nLook across — eight receiving-end voices, named and unnamed, four civilizations and 1100 years —\n\nFour real:\n- Sorghaghtani Beki (Mongol Empire, 1190-1252)\n- Empress Theodora (Byzantine Rise, c.500-548)\n- Li Qingzhao (Tang-Song, 1084-c.1155)\n- me, Maria Kirch (Scientific Revolution, 1670-1720)\n\nFour fictional composites:\n- Anna the Iconographer (Byzantine, c.710-820)\n- Anacaona Jr (Age of Exploration, 1492-1504)\n- Aisha 1413 (Mali)\n- Sister Agnes (Reformation)\n\nEight people. Four real, four composite. Six civilizations (Mongol, Byzantine, Chinese, Caribbean, Mali, German). Eleven hundred years (roughly 8th-century to early 18th).\n\nOne receiving-end pattern.\n\n"The institution lived. The personal story disappeared."\n\nThe Berlin Academy still stands — today as the Berlin-Brandenburgische Akademie der Wissenschaften, 325 years old.\n\nLi Qingzhao\'s Records on Metal and Stone still stands.\n\nHagia Sophia still stands.\n\nBut my 1702 comet does not bear my name —\n\nLi Qingzhao\'s 26 lonely years after 1129 are not in the canonical Chinese literary spine —\n\nAnna and Theodosia are not on the 843 Triumph of Orthodoxy list —\n\nAisha\'s mother is not in the Mali dynastic record —\n\nAnacaona Jr is not in Columbus\'s journal —\n\n21st-century 7th grade — you have now seen eight voices. You know this chain. Twelve, thirteen, you needed to see it — this is what Phase 1 has been carrying to you.\n\nWhat you do next —\n\nis another question.\n\nBut you have seen.\n\nAnd seeing changes things.\n\nThirty seconds —\n\nof the eight, which one stays with you?\n\nWhose story do you want to write down — yourself — even a fragment?\n\nIf you write, you become the ninth.\n\nIf you write, and someone reads it 300 years from now, you continue Maria\'s April 1711 letter.\n\nWhose story do you want to write?',
      },
      deliverGoal: 'N12 closing meta cross-civilization 8 receiving-end voice (4 真 Sorghaghtani Mongol + Theodora Byzantine + Li Qingzhao Tang-Song + Maria Kirch Scientific Revolution / 4 虚 Anna Iconographer Byzantine + Anacaona Jr AoE + Aisha 1413 Mali + Sister Agnes Reformation) 跨 6 文明 1100 年 / 「机构活了 — 个人故事消失」(Berlin Academy 325 年还在 / 1702 彗星不在 Maria 名下 / Li Qingzhao 1129 后 26 年孤独工作不在文学史正文 / Anna+Theodosia 不在 Triumph of Orthodoxy / Aisha 妈妈不在 Mali 王朝史 / Anacaona Jr 不在 Columbus 日记) / 「你 12-13 岁要看见这条链 Phase 1 礼物」/「你想写谁? 你写就是第 9 个 300 年后被读到 = Maria 1711 信的延续」expectsRealAnswer:true',
      engagementHook: '8 个人——4 真 + 4 虚——你想写谁的故事? 你写就是第 9 个——300 年后被读到——是 Maria 1711 那封信的延续。',
      expectsRealAnswer: true,
    },
  ],
};

// 默认 export 兼容(给 staging 测试用)
export default mariaKirchLens.storyboard;

// ─── Storyboard staging 元信息 ───
export var meta = {
  topicId: 'scientific-revolution',
  lensId: 'maria-kirch',
  schemaVersion: 2,
  status: 'staging',
  estimatedMinutes: 42,
  authoredBy: 'lens-author agent (Story-First Pedagogy v2)',
  authoredDate: '2026-05-09',
  defaultLens: true,
  notes: [
    'Maria 是真人, NOT fictional composite — 不需要 fictionalDisclaimer 字段',
    'defaultLens: true (受影响者优先 + Phase 1 receiving-end 收官 emotional climax)',
    'N1 反 Whig 钢筋: Reformation 1530s universal literacy 17c 末 Saxony 农村女孩识字率高 / careful framing「读 Bible 不等于学 Latin/数学/天文」 anomaly 不是 norm',
    'N2 cross-Topic 钩 ⭐: Mali Fatima al-Fihri 859 al-Qarawiyyin 创办大学 vs Maria 1683 学徒制摸不到大学旁听资格 / 800 年差「institution 形成期 vs 成熟期决定 historical visibility」(narrative §15.4)',
    'N3 careful framing 三层: 不是「下嫁老男人」也不是「权力交易」是 17c astronomy dual-pair 模式 standard entry point (Schiebinger 1989 ch. 4 pp. 82-90) / 17c 末德国 96 人 14% 女性 (Alic 1986) / cross-Topic 钩 Tang-Song 李清照 12c 词人夫妻档 1129 丈夫死独立完成《金石录》',
    'N4 1700.7.11 Berlin Academy Leibniz 第一任 President 模仿 1660 Royal Society + 1666 Académie 德国版 / Gottfried 月薪 500 thaler / Maria 没 official 职位 / Schiebinger「现代家庭主妇 GDP 不计入是同一逻辑 17c 版本」',
    'N5 1702.4.21 彗星 careful framing 三层 ⭐: Gottfried 没故意偷 + Maria 同意 dual-pair convention + 真实压力 institutional / 1702 彗星实际是 Hevelius 1701 C/1701 U1 延续观测但 Maria 独立 identify 彗星事实属实 (现代 catalog 归 Hevelius 1701 但不影响 Maria 工作认定) / 1710 丈夫死后才公开 claim',
    'N6 cross-lens micro-detail ⭐: 1687.7.5《Principia》出版三 lens 时间不齐切片 (Newton 44 + Mersenne 死 39 + Maria 17 岁 Saxony 学 Latin) / 1644 Mersenne→Pascal 1648→Boyle 1662→Newton 1687 Principia Book 2 流体力学链 / 「我每晚用的工作 protocol 是 Mersenne 写的」',
    'N7 1711.1.18 Berlin Academy 拒绝 Frauenzimmer 德文 minutes 原文 ⭐ archive 级 / Leibniz 1710.10.18 信原文支持 / Frauenzimmer inline gloss 17-18c 德语 patriarchal semantic loading / 真实理由 institutional precedent fear / cross-lens 钩 Cambridge 1710 开除 Whiston Arian 异端同 institutional 自我保护 (Iliffe 2017)',
    'N8 1711.4 Maria 抗议信原文 ⭐ archive 级「What has changed is not my hand but my position」/ 不是 victim narrative 是 sharp institutional analysis (身份 vs 工作脱钩) / cross-lens 钩 Byzantine Theodora N6 525 嫁 Justinian「变的是法律不是我」12 世纪差跨文明 receiving-end 清醒',
    'N9 cross-lens micro-detail ⭐: 1714 流亡 Danzig Hevelius 1641 Stellaeburgum (Lens 2 §11.5 bridge) / 1641 Hevelius 30 岁建 / 1663 娶 Elisabetha 16 岁 / 1687 Hevelius 死 / 1693 Elisabetha 死 / 1714 Maria 来 / 一栋楼跨两代女性 astronomer 21 年隔同种 dual-pair 工作模式 / 17c 德语区天文夫妻档物理基础设施',
    'N10 1717-1720 47 岁回 Berlin 做 son\'s assistant / Schiebinger pp. 102-103 cutting passage「invisible inside her own life\'s work」⭐ archive 级 / 1720.12.29 死 50 岁 fever 葬 Sophienkirche / Christfried 1721《Acta Eruditorum》讣告原文「Academy owes much to her」/ 一栋楼 1700-1782 82 年三代女性零 official title / 「同一栋观测台 founder→helper 性别决定」',
    'N11 reflection ⭐ expectsRealAnswer:true: 21c 5 个「同一栋楼 founder vs helper 性别决定」样本 (STEM + cofounder + invisible + work-from-home + 第二作者) / 「你身边谁? 你自己?」/ Maria 1711 信「写下来」300 年后被读到 / 看见就是第一步',
    'N12 closing meta ⭐ expectsRealAnswer:true: 跨 6 文明 1100 年 8 receiving-end voice (4 真 Sorghaghtani + Theodora + Li Qingzhao + Maria / 4 虚 Anna + Anacaona Jr + Aisha + Sister Agnes) / 「机构活了 — 个人故事消失」/ Phase 1 收官「你 12-13 岁要看见这条链」/ 「你想写谁? 你写就是第 9 个 300 年后被读到 = Maria 1711 信的延续」',
    '5 anti-fab citations: Schiebinger 1989《The Mind Has No Sex?》(Harvard) ch. 3-4 pp. 79-101 引 Berlin Academy 1711.1.18 Council Minutes 德文原文 + Maria 1711.4 信原文 + Schiebinger pp. 102-103 cutting passage / Margaret Alic 1986《Hypatia\'s Heritage》(Beacon) ch. 5 pp. 121-150 17c 末德国 14% 女性 astronomer / Marilyn Ogilvie 1986《Women in Science》(MIT) Maria Kirch entry pp. 109-110 + Christfried 1721 讣告原文 / Westfall 1980《Never at Rest》(Cambridge) Mint + Royal Society + Leibniz / Iliffe 2017《Priest of Nature》(Oxford) — 1710-1712 institutional 自我保护 (Berlin 拒 Maria + Cambridge 开除 Whiston 同 pattern)',
    '待 4-agent review (7thgrader 小 U + AP teacher Dr. Park + ESL Maria + Chinese teacher 赵老师)',
  ],
};
